import type { Lesson } from "@/types/content";

/**
 * Kindergarten — the printed 2023 edition, chapter by chapter.
 *
 * Titles, descriptions and objectives are read off the pages. The book prints
 * no per-lesson titles of its own: each lesson opens with a blue "Objectives
 * of the lesson N" bar, so a title here is either that bar's first objective
 * or a section heading printed on the page — never invented.
 *
 * Every lesson is anchored to its pages (see content/page-anchors.ts), so a
 * four-year-old's lesson opens as the spread it actually is.
 */

// ------------------------------------------------------------------------
// knowingComputerLessons
// ------------------------------------------------------------------------

export const knowingComputerChapterSummary: string =
  "Chapter 1 is a four-year-old's first sitting at a computer: seven short lessons that name the only parts the book shows — a mouse, a laptop, a screen, a keyboard and a tablet — and then spend the rest of the chapter putting a hand on the mouse. Every lesson pairs a page of pictures with a GCompris drill (Baby mouse, Move the mouse, Click on me, Click or tap, Click and draw, Mouse click training, Complete the puzzle, Double tap or double click, Penalty kick, Baby keyboard, Numbers with dice), so the child practises moving, clicking, right-clicking, dragging, double-clicking and pressing letter and number keys. Each lesson closes with the same 'Moving the dog' grid, where the child fills empty squares with arrow moves until the dog reaches its food — the chapter's first algorithm.";

export const knowingComputerLessons: Lesson[] = [
  {
    id: "g0-kc-01",
    slug: "discovering-the-main-parts-of-a-computer",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 1,
    title: "Discovering the Main Parts of a Computer",
    description: "Name the five computer parts the book shows — a mouse, a laptop, a screen, a keyboard and a tablet — then meet GCompris, the program used for every mouse activity in the chapter.",
    objectives: [
      "Discovering the main parts of a computer",
      "Discovering the GCompris program",
      "Mastering the use of the mouse",
      "My Computer: \"At home, I use a computer to study and to play.\" — Do you have a computer at home? Yes / No. Who uses it? Me / My parents",
      "Knowing my computer: link each name to its picture — A Mouse, A Laptop, A Screen, A Keyboard, A Tablet",
      "I draw my computer: draw a computer screen and draw a computer mouse in the empty box beside each model",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-02",
    slug: "practicing-the-use-of-the-mouse",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 2,
    title: "Practicing the Use of the Mouse",
    description: "Steer a duck across water by moving the mouse in four directions, sweep the pointer over green bricks to uncover a hidden animal, and fill arrow moves into a grid so the dog reaches its food.",
    objectives: [
      "Practicing the use of the mouse",
      "Solving a simple algorithm",
      "Moving the mouse: \"The Baby mouse activity allows you to master the movement of the mouse in the four directions\" — click on Baby mouse, then move the computer mouse in the 4 directions to move the duck",
      "What's behind the blocks?: \"Move the mouse over the bricks to discover the hidden animal\" — click on \"Move the mouse\", move the mouse over the green bricks, discover the hidden animal, then name the animal (A dog / A cat / A horse / A duck)",
      "Moving the dog: \"The dog can move in 4 directions\" — ← the dog moves forward, → the dog moves backward, ↓ the dog moves down, ↑ the dog moves up",
      "Fill in the squares with the right moves to make the dog reach the food (one grid on each of the two pages)",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-03",
    slug: "mastering-the-use-of-the-mouse-click",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 3,
    title: "Mastering the Use of the Mouse Click",
    description: "Click fish before they swim off the screen, tap green bricks to uncover a bird, click green dots to draw a shape, then solve another dog-and-food grid.",
    objectives: [
      "Mastering the use of the mouse click",
      "Solving a simple algorithm",
      "Click on me: \"The 'Click on me' activity allows you to master the click of the mouse\" — click on the fish before it shows on the screen",
      "Click on Click or tap, then click on the green bricks to discover the animal behind",
      "Drawing with the mouse: \"The Click and draw activity allows you to master the click of the mouse while drawing shapes\" — click on the green dots to draw the shape",
      "Moving the dog: the dog can move in 4 directions — fill in the squares with the right moves to make the dog reach the food",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-04",
    slug: "left-click-right-click",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 4,
    title: "Left Click, Right Click",
    description: "Learn what each mouse button does — the left button sends the fish to the lake, the right button sends the monkey to the tree — then click and drag objects onto their matching shapes.",
    objectives: [
      "Mastering the use of the mouse click",
      "Making the difference between the left and right click",
      "Showing the animal: \"The Click or tap activity allows you to master the click of the mouse\" — click on the green bricks to show the hidden animal",
      "Left click, right click: click on Mouse click training — use the left button to move the fish to the lake, and use the right button to move the monkey to the tree",
      "Completing the puzzle: \"The Complete the puzzle activity allows you master the click and drag of the mouse while matching shapes\" — move the object to its corresponding shape",
      "Moving the dog: the dog can move in 4 directions — fill in the squares with the right moves to make the dog reach the food",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-05",
    slug: "mastering-the-use-of-the-double-click-of-the-mou",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 5,
    title: "Mastering the Use of the Double Click of the Mouse",
    description: "Practise the double click: uncover a giraffe brick by brick, take a penalty kick into the left or right corner, then mark the mouse and the keyboard on a photo.",
    objectives: [
      "Mastering the use of the double click of the mouse",
      "Solving a simple algorithm",
      "Showing the animal: \"The Double tap or double click activity allows you to master the double click of the mouse\" — click on Double tap or double click, then double click on the bricks to show the hidden animal",
      "Playing football: click on Penalty kick, double click on the left button where you want to kick the ball, and choose the left or right corner",
      "Exercise: \"Write the following words 3 times: mouse - screen - computer\"",
      "Mark the mouse with (1) and the keyboard with (2) on the photograph",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-06",
    slug: "the-computer-is-everywhere",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 6,
    title: "The Computer Is Everywhere",
    description: "See the five places the book shows computers at work — hotel, restaurant, airport, hospital and factory — talk about why you use one at school and at home, then press letter keys in GCompris Baby keyboard.",
    objectives: [
      "Learning where a computer is used",
      "Discovering the computer keyboard keys",
      "Solving a simple algorithm",
      "The computer is everywhere: \"Computers are used in different tasks\" — At the hotel, At the restaurant, At the airport, At the hospital, At the factory",
      "The computer at school: Why do I use a computer at school? Why do I use a computer at home?",
      "Typing letters: \"The Baby keyboard activity allows you to master the typing of letters using the keyboard\" — click on Baby keyboard, then press a letter on the keyboard to hear it and to print it on the screen",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kc-07",
    slug: "mastering-the-use-of-the-numerical-keys-of-the-k",
    gradeId: "g0",
    unitId: "g0-knowing-computer",
    order: 7,
    title: "Mastering the Use of the Numerical Keys of the Keyboard",
    description: "Press the number keys 1 and 2 as they appear on dice falling from the sky in GCompris, then solve the last dog-and-food grid of the chapter.",
    objectives: [
      "Mastering the use of the numerical keys of the keyboard",
      "Solving a simple algorithm",
      "\"The Numbers with dice activity allows you to master the typing of numbers using the keyboard\" — click on Numbers with dice",
      "Type the number 1 or 2 as they appear on the dice",
      "Moving the dog: the dog can move in 4 directions — fill the squares with the correct moves to make the dog reach the food",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// cartoonLessons
// ------------------------------------------------------------------------

export const cartoonChapterSummary: string =
  "Chapter 2 teaches drawing before it teaches any software: four lessons that move from tracing dashed lines and joining dots, to copying a picture square by square on a lettered grid, to building whole characters out of a handful of simple shapes. Every worksheet page is followed by a page of dot paper where the child draws numbers, letters, flowers, robots, animals and cartoons, and each of those pages closes with the same instruction — practise the same drawing again in the program Paint. There is almost no text on any page: the child traces, joins, copies, builds and colours.";

export const cartoonLessons: Lesson[] = [
  {
    id: "g0-cd-01",
    slug: "connecting-the-dots",
    gradeId: "g0",
    unitId: "g0-cartoon-drawing",
    order: 1,
    title: "Connecting the Dots",
    description: "Copy a house and a robot dot by dot onto an empty dot grid, join a numbered dot-to-dot into a robot and colour it, then draw the numbers 1-2-3-4 and the letters L-P-C-B on dot paper and again in Paint.",
    objectives: [
      "Connect the dots on the right to match the drawing on the left.",
      "Connect the dots to finish drawing the robot then color it.",
      "Draw the numbers 1 - 2 - 3 - 4.",
      "Draw the letters L - P - C - B.",
      "Practice the above drawings on the program Paint.",
    ],
    skillIds: ["cr-projects"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Palette",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-cd-02",
    slug: "copying-by-grid",
    gradeId: "g0",
    unitId: "g0-cartoon-drawing",
    order: 2,
    title: "Copying by Grid",
    description: "Use a lettered six-row grid to finish half-drawn pictures — a castle and a waving astronaut — then copy a whole rocket-and-planet picture square by square, and build flowers and robots from simple shapes.",
    objectives: [
      "Look at the grid drawing and try to complete the other half.",
      "Look at the grid above and try to copy it onto the second grid below. Have Fun!!",
      "Use different shapes to draw flowers.",
      "Use different shapes to draw robots.",
      "Practice the above drawings on the program Paint.",
    ],
    skillIds: ["cr-projects"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Palette",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-cd-03",
    slug: "creating-with-shapes",
    gradeId: "g0",
    unitId: "g0-cartoon-drawing",
    order: 3,
    title: "Creating with Shapes",
    description: "Build a cat and an owl out of the seven shapes printed at the top of the page, follow steps A to F to assemble a dinosaur and colour it, then draw a cat, a dog face, a bear, a sun, a butterfly and a mushroom.",
    objectives: [
      "Draw the characters below using shapes and lines!",
      "Follow the steps above to build your dinosaur. Have fun coloring!",
      "Use different shapes to draw a cat.",
      "Use different shapes to draw a dog face.",
      "Use different shapes to draw the head of a bear and the sun.",
      "Use different shapes to draw a butterfly and a mushroom.",
    ],
    skillIds: ["cr-projects"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Palette",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-cd-04",
    slug: "using-lines-shapes",
    gradeId: "g0",
    unitId: "g0-cartoon-drawing",
    order: 4,
    title: "Using Lines & Shapes",
    description: "Watch a lion, a truck and an ice cream grow over four steps from plain shapes, finish an unfinished robot and birthday cake, then fill a run of dot-paper pages with cartoons.",
    objectives: [
      "Use lines and shapes to create the objects below.",
      "Use lines and shapes to finish the characters above.",
      "Use different shapes to draw a tree and an ice cream",
      "Use different shapes to draw a lamp and a tap.",
      "Use different shapes to draw a cake and a bicycle.",
      "Use different shapes to draw a moon and a car.",
    ],
    skillIds: ["cr-projects"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Palette",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// keyboardLessons
// ------------------------------------------------------------------------

export const keyboardChapterSummary: string =
  "Chapter 3 puts a real keyboard under the child's fingers. Five lessons move from naming the screen, keyboard and mouse and filling in the missing letters on a QWERTY keyboard picture, to typing single letters and then short three-letter words as they fall down the GCompris screen, and on to tracing, counting, sequencing and ordering numbers. Every lesson closes with an unplugged \"Moving the dog\" page where the child follows a row of arrows across a 7x7 picture grid and circles the drawing the dog reaches.";

export const keyboardLessons: Lesson[] = [
  {
    id: "g0-kb-01",
    slug: "my-computer-discovering-the-keyboard",
    gradeId: "g0",
    unitId: "g0-keyboard",
    order: 1,
    title: "My Computer — Discovering the Keyboard",
    description: "Name the three parts of a computer, fill in the missing letters on a picture of a QWERTY keyboard, then type single letters as they fall in GCompris.",
    objectives: [
      "Identifying the main parts of a computer",
      "Identifying the keyboard keys",
      "Using GCompris to master the keyboard",
      "Match the screen with number 1, the keyboard with number 2 and the mouse with number 3 on the picture of the computer",
      "Look at a computer keyboard then fill in the missing letters — only Q and P (top letter row), A (home row) and Z and M (bottom row) are printed",
      "Launch GCompris and click on Simple letters",
    ],
    skillIds: ["dl-files", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Keyboard",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kb-02",
    slug: "typing-words-drawing-numbers",
    gradeId: "g0",
    unitId: "g0-keyboard",
    order: 2,
    title: "Typing Words — Drawing Numbers",
    description: "Move up from single letters to typing whole three-letter words, then trace the shape of a number by dragging the mouse over a trail of green dots.",
    objectives: [
      "Mastering typing word",
      "Mastering drawing numbers using GCompris",
      "Solving simple algorithm",
      "Launch GCompris and click on Falling words, then type the whole word before it lands (joy, lie, nor, say — the counter runs 0/15)",
      "Launch GCompris, click on the Numeration category, then click on Draw numbers",
      "Move the mouse over the green dots to draw the number",
    ],
    skillIds: ["dl-files", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Keyboard",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kb-03",
    slug: "counting-numbers-sequence-and-ordering-numbers",
    gradeId: "g0",
    unitId: "g0-keyboard",
    order: 3,
    title: "Counting Numbers — Sequence and Ordering Numbers",
    description: "Three GCompris number games in a row: colour the right number of circles, join the dots in number order, and drag numbers into ascending order.",
    objectives: [
      "Counting numbers using GCompris",
      "Practicing the sequence of numbers",
      "Practicing placing numbers by order",
      "Launch GCompris, click on Count and colour the circles, then click on one circle and on \"OK\"",
      "Launch GCompris, click on the Numeration category, then on Number sequence, and click on the number following the order",
      "Launch GCompris, click on the Numeration category, then on Ordering numbers, and move the numbers by order from bottom to top",
    ],
    skillIds: ["dl-files", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Keyboard",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kb-04",
    slug: "counting-numbers-visual-counting-and-finding-t",
    gradeId: "g0",
    unitId: "g0-keyboard",
    order: 4,
    title: "Counting Numbers — Visual Counting and Finding the Path",
    description: "Count objects and type the answer on the keyboard, add two small numbers by tapping circles, then decode an arrow path square by square.",
    objectives: [
      "Counting numbers using GCompris",
      "Building an algorithm to find a path",
      "Solving a simple algorithm",
      "Launch GCompris, click on Count the items, count the apples then type the corresponding number",
      "Launch GCompris, click on the Numeration category, then on Arithmetic, then on Learn additions",
      "Add the two numbers then click on the circles that correspond to their sum",
    ],
    skillIds: ["dl-files", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Keyboard",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-kb-05",
    slug: "path-finder-moving-the-dog",
    gradeId: "g0",
    unitId: "g0-keyboard",
    order: 5,
    title: "Path Finder — Moving the Dog",
    description: "A single-page closing lesson: drag the right arrow into the sequence so the penguin walks its path, then one last paper arrow-following grid.",
    objectives: [
      "Drawing a path using GCompris",
      "Solving a simple algorithm",
      "It is now time to learn how to move the penguin on a path",
      "Launch GCompris, click on the penguin category, then on Logic, then on Path decoding",
      "Move the correct arrow to make the penguin move on its path",
      "The dog can move in 4 directions — follow the arrows and circle the drawing the dog will reach",
    ],
    skillIds: ["dl-files", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Keyboard",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// paintLessons
// ------------------------------------------------------------------------

export const paintChapterSummary: string =
  "Chapter 4 opens Microsoft Paint and lets the child draw. Eight lessons introduce one tool at a time — the Brush with the colour palette, the built-in Shapes gallery (line, curve, rectangle, circle and oval), the Fill-with-colour bucket, and the freehand Pen with its Size setting — and each new tool is spent immediately on a picture: a sun, a house, a car, a boat, a dog's face, an ice cream, a cake, and eight plain circles turned into eight different faces. Every lesson ends the same way, with a strip of \"ideas to get inspired\" and an empty box where the child draws the picture themselves.";

export const paintLessons: Lesson[] = [
  {
    id: "g0-pt-01",
    slug: "drawing-with-paint-drawing-the-sun",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 1,
    title: "Drawing with Paint — Drawing the Sun",
    description: "Find the Paint icon, learn the two halves of its welcome screen, pick a colour, and draw a sun with the Brush.",
    objectives: [
      "Discovering the welcome screen of the Paint program",
      "Using the Brush tool to draw a sun",
      "Paint is a program to draw shapes",
      "The icon Paint",
      "The welcome screen: 1- The drawing tools, 2- The page to draw",
      "To start drawing, select the colours: click on Brushes, click on Color 1, choose a colour, start your drawing",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-02",
    slug: "drawing-shapes-drawing-a-house",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 2,
    title: "Drawing Shapes — Drawing a House",
    description: "Open the Shapes gallery, draw a square, a circle, a rectangle and a curved line, then combine shapes into a house.",
    objectives: [
      "Discovering the built in shapes in Paint",
      "Drawing coloured shapes",
      "Using the Paint shapes to draw a house",
      "Use Paint to draw shapes: click on Shapes, then examine the different shapes",
      "Draw a square, draw a circle, draw a rectangle, draw a curved line",
      "It is time to draw coloured shapes: click on Shapes, select the circle, select the red colour, draw a circle",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-03",
    slug: "drawing-free-shapes-drawing-a-car",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 3,
    title: "Drawing Free Shapes — Drawing a Car",
    description: "Work with the Line shape alone: draw a stair, an ice cream, a house and a sun out of straight lines, then a car.",
    objectives: [
      "Using the line tool to draw shapes",
      "Drawing free shapes",
      "Drawing a car",
      "Use Paint to draw shapes: click on Shapes, examine the different shapes, use the shape Line",
      "Draw a stair, draw an ice cream, draw a house, draw a sun",
      "It is time to draw free shapes: click on Shapes, select the line tool, draw a free shape",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-04",
    slug: "filling-in-colours-drawing-a-boat",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 4,
    title: "Filling in Colours — Drawing a Boat",
    description: "Meet the Fill-with-colour bucket by turning an empty rectangle red, then paint a whole boat scene with filled shapes.",
    objectives: [
      "Using Paint tool to change the colour of a drawing",
      "Drawing a boat",
      "Use Paint to change the colour of your drawing",
      "Draw a rectangle, select a colour, click on the Fill with colour tool, click inside the rectangle, examine the red rectangle",
      "It is time to draw a boat: use the rectangle to draw the sea",
      "Use the rectangle to draw a yellow sky",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-05",
    slug: "using-the-pen-tool-drawing-a-dog-face",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 5,
    title: "Using the Pen Tool — Drawing a Dog Face",
    description: "Choose the Pen and its line width, draw a dog's face completely freehand, then fill each part with a different colour.",
    objectives: [
      "Drawing a dog face",
      "Drawing the sun",
      "Use Paint to draw a dog face",
      "Click on the Pen, click on Size, select the width",
      "Draw a dog face",
      "Use the Fill with colour tool to colour the face, then examine the dog face",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-06",
    slug: "using-the-pen-tool-drawing-an-ice-cream",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 6,
    title: "Using the Pen Tool — Drawing an Ice Cream",
    description: "Build an ice cream out of stacked line-drawn bands and three overlapping ovals, colouring every part, then draw a cake.",
    objectives: [
      "Drawing an ice cream",
      "Drawing a cake",
      "Use Paint to draw an ice cream",
      "Click on Shapes, select the Line, draw the corn",
      "Use the Fill with colour tool to colour the corn, then examine the corn",
      "The flavours on TOP: click on Shapes, select the Oval, draw 3 ovals as shown",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-07",
    slug: "using-the-pen-drawing-a-house",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 7,
    title: "Using the Pen — Drawing a House",
    description: "An eight-step, follow-along build: line by line the child draws a house outline, its roof lines, borders, door and windows, then colours it and adds sky.",
    objectives: [
      "Discovering the steps to draw a house",
      "Use Paint to draw a house",
      "Click on Shapes, select the Line",
      "Draw the shape",
      "Add two lines",
      "Complete the borders",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-pt-08",
    slug: "drawing-faces",
    gradeId: "g0",
    unitId: "g0-paint",
    order: 8,
    title: "Drawing Faces",
    description: "Draw eight identical circles with the Oval tool, then turn each one into a different creature and colour them all in.",
    objectives: [
      "Drawing different shapes using the circle tool",
      "Use a circle to draw different shapes",
      "Click on Shapes, select the Oval",
      "Draw 8 circles",
      "Create different shapes",
      "Colour the shapes",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// algorithmLessons
// ------------------------------------------------------------------------

export const algorithmChapterSummary: string =
  "Chapter 5 teaches an algorithm as an ordered list of steps, almost entirely by tapping, dragging and colouring — there is nothing for the child to read beyond the one instruction line an adult reads aloud. Four lessons work inside the free GCompris suite: copying a five-step flower drawing in Paint, decoding a row of arrow tokens to trace a penguin's path to a red flag, continuing repeating fruit patterns, assembling picture puzzles (a train from its shadows, a tangram bird), mirroring coloured squares across a grid and rebuilding a mosaic in the right order. Every lesson closes with a pencil-and-paper version printed in the book: walking a man across a 7x7 picture grid by following arrow cards, or mirroring a pattern of coloured squares.";

export const algorithmLessons: Lesson[] = [
  {
    id: "g0-al-01",
    slug: "drawing-a-flower-and-following-a-path",
    gradeId: "g0",
    unitId: "g0-algorithms",
    order: 1,
    title: "Drawing a Flower and Following a Path",
    description: "Copy a flower in five numbered Paint steps, then open GCompris and read a row of arrow tokens to trace the penguin's path to the red flag.",
    objectives: [
      "Discovering the steps to draw a flower",
      "Using GCompris to draw a path for the penguin",
      "Solving an algorithm",
      "Follow the 5 numbered steps in the Paint screenshot to draw a flower — the left column of the book prints only 'Step 1.' to 'Step 5.', the pictures carry the whole instruction",
      "Launch GCompris, click the penguin (Logic section), then click the 'Path decoding' activity",
      "The penguin must reach the red flag: click on the green squares on the map to draw the path of the penguin in the same order shown by the arrows",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-al-02",
    slug: "completing-the-list-and-the-puzzle",
    gradeId: "g0",
    unitId: "g0-algorithms",
    order: 2,
    title: "Completing the List and the Puzzle",
    description: "Continue a repeating fruit pattern in GCompris, rebuild a train from its shadow shapes, then walk the man across the paper grid again.",
    objectives: [
      "Using GCompris to solve an algorithm",
      "Using GCompris to match shapes",
      "Solving a simple algorithm",
      "Examine the first line of fruits, examine the missing fruits on the second line, then complete the missing fruits on line 2",
      "Baby Puzzle is an activity to enhance visual matching — place each picture in its corresponding shape",
      "Follow the 7 arrow cards on paper and circle the drawing the man reaches",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-al-03",
    slug: "mirroring-a-drawing",
    gradeId: "g0",
    unitId: "g0-algorithms",
    order: 3,
    title: "Mirroring a Drawing",
    description: "Copy a pattern of coloured squares onto the mirror half of a GCompris grid, cover a bird silhouette with tangram shapes, then mirror square patterns with coloured pencils.",
    objectives: [
      "Using GCompris to complete mirrored shapes",
      "Using GCompris to build a puzzle",
      "Mirror the Given image is an activity to enhance visual drawing",
      "Examine the red squares on the right table, then reproduce the same drawing on the left table",
      "Tangram puzzle game is an activity to enhance visual matching — move the shapes to cover the grey area",
      "Use a red pencil to create the mirror shape of the table on the left",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-al-04",
    slug: "rebuilding-the-mosaic",
    gradeId: "g0",
    unitId: "g0-algorithms",
    order: 4,
    title: "Rebuilding the Mosaic",
    description: "Drag pictures into the right order to match a model row in GCompris, then finish a last mirrored-square pattern on paper.",
    objectives: [
      "Using GCompris to rebuild a mosaic",
      "Practicing building mirrored shapes",
      "Rebuild the mosaic is an activity to enhance visual ordering",
      "Examine the order of the drawings, then move the drawings in the correct order",
      "Use a red pencil to create the mirror shape of the table on the left",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// scratchJrLessons
// ------------------------------------------------------------------------

export const scratchJrChapterSummary: string =
  "Chapter 6 gives the child their first real programming environment: ScratchJr, where every block is a picture and nothing has to be read. Five lessons take them from opening the app and snapping a green flag onto a blue arrow block so the sprite TIC walks five steps, through reading TIC's square on the numbered stage grid and predicting where a short chain of move blocks will land him, to changing the background from the picture library, adding and deleting sprites, giving a sprite a speech bubble, and finishing with a soccer ball that hops five times in the gym. The ideas are sequence, step counts and run-it-and-see — all built by dragging icons into a horizontal strip.";

export const scratchJrLessons: Lesson[] = [
  {
    id: "g0-sj-01",
    slug: "launching-scratch-junior",
    gradeId: "g0",
    unitId: "g0-scratchjr",
    order: 1,
    title: "Launching Scratch Junior",
    description: "Open ScratchJr, start a new project, and snap a green flag onto a blue move block so TIC walks five steps.",
    objectives: [
      "Discovering the welcome screen of ScratcJr",
      "Making Tic move its first steps",
      "Click on Scratch Junior and examine the welcome screen",
      "Click on the home button, then click on the '+' card to open a new project",
      "Examine the welcome screen of Scratch Junior",
      "To make TIC walk, follow the steps below",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-sj-02",
    slug: "tic-moving-in-all-directions",
    gradeId: "g0",
    unitId: "g0-scratchjr",
    order: 2,
    title: "TIC Moving in All Directions",
    description: "Read TIC's square off the numbered stage grid, then run four one-block missions and a four-block mission and say where he lands each time.",
    objectives: [
      "Tic walking on the grid",
      "Identify the coordinates of the Sprite Tic",
      "TIC moves on the grid — examine the position (8-11)",
      "Move the two blocks, then locate the position of TIC on the grid",
      "Project to do: build the mission, then draw the arrows in the yellow circles to show how TIC moves on the grid",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-sj-03",
    slug: "a-new-background-picture",
    gradeId: "g0",
    unitId: "g0-scratchjr",
    order: 3,
    title: "A New Background Picture",
    description: "Swap the stage background from the picture library, then add the missing move blocks until TIC reaches the door of the house.",
    objectives: [
      "Placing a new picture on the Background of the scene",
      "Ordering Tic to reach a target",
      "To change the picture of the background: click on the background button, select a picture, click on the tick, then examine the result",
      "Click on TIC and drag it to the position (3-3)",
      "TIC must arrive at the door — the position of the door is (7-13)",
      "Add the missing blocks to make TIC reach the door",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-sj-04",
    slug: "adding-a-new-sprite",
    gradeId: "g0",
    unitId: "g0-scratchjr",
    order: 4,
    title: "Adding a New Sprite",
    description: "Add Tac from the character library, delete TIC, walk Tac to the tree in the park and give him a speech bubble.",
    objectives: [
      "Adding a new Sprite",
      "Deleting a Sprite",
      "Making the Sprite talk",
      "Add Tac to the project: click on '+', select Tac, click on the tick",
      "Click and hold on Tic, then click on the red X to delete Tic",
      "Add the Park picture, click on Tac and drag it to the position (13-3), then build the mission to make Tac reach the tree",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g0-sj-05",
    slug: "jumping-ball",
    gradeId: "g0",
    unitId: "g0-scratchjr",
    order: 5,
    title: "Jumping Ball",
    description: "Add a soccer ball and the gym background, then chain five hop blocks so the ball bounces higher and higher.",
    objectives: [
      "Discovering the Jump block",
      "Making the ball jump",
      "Tic plays soccer ball",
      "Add the ball, add the Background Gym, place Tac and the Soccer Ball",
      "Build the mission, click on the green flag — the ball is jumping",
      "Extra project: modify the mission to make the ball jump while moving left and right",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
];
