import type { Lesson } from "@/types/content";

/**
 * Grade 2 — the printed 2023 edition, chapter by chapter.
 *
 * Titles, descriptions and objectives are read off the pages. Where the book
 * prints no lesson title of its own, the title is its first stated objective
 * or a heading printed on the page — never invented.
 */

// ------------------------------------------------------------------------
// g2-ch1 — componentsLessons
// ------------------------------------------------------------------------

export const componentsChapterSummary: string =
  "Chapter 1 is five sittings, printed pages 3 to 12, that turn last year's three parts into a whole machine. It names seven components in words and photos — the case (system unit), the screen, the keyboard, the mouse, the microphone, the speakers and the printer — adds a bar-code reader, web camera, headphones and scanner in the final review, and sorts them all into Input Units, the System Unit and Output Units. The child learns that a computer is an electronic machine that processes information (text, image, sound, film, numbers), traces the arrows of information going in and coming out, and drills at the keyboard and mouse in GCompris with \"Fallen Words\" and \"Click and draw\".";

export const componentsLessons: Lesson[] = [
  {
    id: "g2-co-01",
    slug: "reviewing-the-skills-acquired-in-grade-1",
    gradeId: "g2",
    unitId: "g2-components",
    order: 1,
    title: "Reviewing the Skills Acquired in Grade 1",
    description: "Recall where computers are found, who uses them and what they are for, then complete the list of components, copy a keyboard and a mouse into empty boxes, label four numbered parts on a photo, and type falling words in GCompris.",
    objectives: [
      "Objective of the lesson : Reviewing the skills acquired in Grade 1",
      "Introduction: \"Last year, you discovered the main parts of the computer as well as the places where it is used.\"",
      "1 Where is a computer found? \"List the places you have visited and where the computer is used.\" A computer is used — \"At school\" (given), three tick-boxes left blank",
      "2 Who uses a computer? \"Name professions where the computer is used.\" A computer is used — \"By the teacher\" (given), three tick-boxes left blank",
      "3 Who invented the computer? \"The computer is a machine created by ………… to perform simple and complexe tasks.\"",
      "4 What is the computer used for? \"The computer is used for specific purposes:\" \"To study\" (given) and three blank lines",
    ],
    skillIds: ["sys-hardware"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cpu",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-co-02",
    slug: "mastering-the-use-of-the-mouse-identifying-the-u",
    gradeId: "g2",
    unitId: "g2-components",
    order: 2,
    title: "Mastering the Use of the Mouse — Identifying the Use of a Computer",
    description: "Say what the student, engineer, restaurant and teacher use a computer for, match four places to four jobs, draw with the mouse in GCompris \"Click and draw\", join the dots to draw a mouse and a screen, and compare the first computers with today's.",
    objectives: [
      "Objectives of the lesson: Mastering the use of the mouse - Identifying the use of a computer",
      "1 Introduction: \"In the previous lesson, you learned about the different uses of the computer.\" The student uses it to … / The engineer uses it to … / In a restaurant, the computer is used to … / The teacher uses the computer to …",
      "2 Exercise: \"The computer is used\" — In a pharmacy / In a school / At the airport / In a restaurant — to calculate the average of the marks / to book a plane ticket / to calculate drug prices / to calculate the meal bill",
      "3 Mastering the use of the mouse: \"When you launch GCompris, all activities are displayed.\" \"Click on \\\"Click and draw\\\" to practise the activities that allow you to master the use of the mouse.\"",
      "\"Visit www.zero1.education to download GCompris.\"",
      "4 Exercise: \"The computer is used for various purposes. Rewrite the sentences below:\" A computer is used to draw / A computer is used to write a document / A computer is used to study",
    ],
    skillIds: ["sys-hardware"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cpu",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-co-03",
    slug: "introducing-the-information-that-the-computer-pr",
    gradeId: "g2",
    unitId: "g2-components",
    order: 3,
    title: "Introducing the Information That the Computer Processes — Identifying the Components of the Computer",
    description: "Meet the four kinds of information a computer handles — text, image, sound and video — copy the conclusion that a computer is an electronic machine that processes information, then name seven components from photographs.",
    objectives: [
      "Objectives of the lesson: Introducing the information that the computer processes - Identifying the components of the computer",
      "1 Introduction: \"The computer processes information such as:\" text / Image / Sound / Video",
      "\"The text is a letter to a friend, an exam prepared by the teacher or the lyrics of a song. The photo is taken from the camera or from a mobile phone. The sound is a voice message or a song. The film is an advertisement, a cartoon or a serie.\"",
      "Conclusion: \"We can conclude that the computer is used to process information.\"",
      "\"At home, computer games are made up of images and sounds. In the office, letters and documents are information. In a restaurant, the bill contains information and a calculation processed by a computer.\"",
      "Conclusion... to remember: \"1- A computer is an \\\"electronic machine that processes information\\\". 2- The information that a computer can process is: a text, an image, a sound, a film and numbers.\"",
    ],
    skillIds: ["sys-hardware"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cpu",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-co-04",
    slug: "understanding-how-information-flows-through-the-",
    gradeId: "g2",
    unitId: "g2-components",
    order: 4,
    title: "Understanding How Information Flows Through the Computer",
    description: "Follow information from the keyboard, mouse and microphone into the System Unit and back out to the screen and printer, then sort every component into Input Units, System Unit and Output Units.",
    objectives: [
      "Objective of the lesson: Understanding how information flows through the computer",
      "1 Introduction: \"The computer is an electronic machine that works in a very simple way.\"",
      "\"1- Information enters the computer System Unit through components such as the keyboard. 2- The information is processed inside the System Unit. 3- The information comes out of the System Unit to be displayed on the screen or the printer.\"",
      "\"The picture below shows how information flows through the various components of a computer.\"",
      "2 Summary: \"The keyboard is used to write a document which appears on the screen\" / \"The microphone is used to record a voice then listen to it through headphones\" / \"The mouse is used to draw and the drawing appears on the screen\" / \"On the screen we watch cartoons and movies\"",
      "3 Recapitulation (Important): \"The computer components are divided into 3 categories.\" Input Units (keyboard, microphone, mouse) — System Unit (the case) — Output Units (screen, printer)",
    ],
    skillIds: ["sys-hardware"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cpu",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-co-05",
    slug: "reviewing-the-notions-acquired-in-this-chapter",
    gradeId: "g2",
    unitId: "g2-components",
    order: 5,
    title: "Reviewing the Notions Acquired in This Chapter",
    description: "Recap that a person is the source of all information, that it enters through input devices, is processed in the System Unit and leaves through output devices, then complete the half-written name under each device and draw the arrows of the flow.",
    objectives: [
      "Objectives of the lesson : Reviewing the notions acquired in this chapter",
      "1 Recapitulation: \"From the illustration on the previous page, you understand that:\"",
      "\"1- Man is the source of all information. He is the one who writes, draws and records videos and sounds.\"",
      "\"2- The information is entered into the Computer System Unit through the input devices (mouse - keyboard - microphone).\"",
      "\"3- The information enters the Computer System Unit where it is processed or recorded.\"",
      "\"4- The information comes out in its final form through the output devices (screen - printer - speakers).\"",
    ],
    skillIds: ["sys-hardware"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cpu",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g2-ch3 — algorithmsLessons
// ------------------------------------------------------------------------

export const algorithmsChapterSummary: string =
  "Chapter 3, \"Programming with algorithms\", runs printed pages 26 to 42 as nine lessons that begin with hardware versus software and the everyday algorithm — preparing a salad, drawing a flower, folding a paper airplane — and end inside the Blockly Games Maze. Its heart is a cat on a 10x10 grid with a food plate and coloured squares it cannot cross: the child fills printed boxes with command cards, first Move forward / Move backward / Turn right / Turn left, then cards worth one, two or three steps at once. The later lessons add lettered-and-numbered addresses (A-J, 1-10), point squares that must be collected inside a fixed move budget, a monkey choosing between three numbered plates, two characters running two programs on one board, a square drawn by repeating one set of moves four times, and finally the \"repeat until\" and \"if path\" blocks in Blockly Games Maze levels 1 to 7.";

export const algorithmsLessons: Lesson[] = [
  {
    id: "g2-al-01",
    slug: "hardware-software-and-defining-an-algorithm",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 1,
    title: "Hardware, Software and Defining an Algorithm",
    description: "Sort computer parts into hardware and software by finding the odd one out in each circle, learn that an algorithm is a series of instructions, then write the steps for making a salad, drawing a flower and folding a paper airplane.",
    objectives: [
      "Objectives of the lesson : Introducing computer hardware and software - Defining an algorithm",
      "Introduction: \"A computer is made up of: 1- Hardware (mouse, keyboard,...) 2- Software (paint, scratch, ...)\" — \"List some computer hardware: ______\"",
      "Find the odd: a yellow circle holding a printer (1), Microsoft Word (2) and Paint (3), and a green circle holding a keyboard (1), GCompris (2) and a mouse (3); the child writes the odd one out of each",
      "Software: \"A computer software is used for different reasons: The Paint program is used to draw. The WordPad program is used to write a document. The Scratch program is used to learn coding. The software ______ is used for ______\"",
      "Algorithms: \"Algorithm is a series of instructions to perform an action.\" — illustrated by three photographs: Prepare a salad / Draw a flower / Make a paper airplane",
      "Becoming a programmer: \"Before you start programming, you need to learn algorithm skills that enable you to write a sequence of instructions.\" \"Explore your algorithm skills.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-02",
    slug: "folding-an-airplane-reading-table-coordinates-an",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 2,
    title: "Folding an Airplane, Reading Table Coordinates and a Crossword",
    description: "Fold a real paper airplane by copying five numbered photographs, then read the address of coloured squares off two 6x6 tables lettered A-F down and numbered 1-6 across, and complete a crossword of the three computer components.",
    objectives: [
      "Objectives of the lesson : Making a carft airplane - Identifying the coordinates of a table - Practising crossword puzzles (the book prints \"carft\" for \"craft\")",
      "The stages of making a craft airplane: \"To make a craft airplane, follow the steps below:\" — five circular photographs of a sheet of paper being folded, numbered 1 to 5",
      "\"It is your turn to take a sheet of paper and make a craft airplane by following the steps indicated above.\"",
      "Identifying a table coordinates: \"Examine the table. It is divided into squares. Each one has an address composed of a letter and a number.\"",
      "\"Determine the address of the squares. The red square is on A2 / The blue square is on ____ / The green square is on ____ / The yellow square is on ____ / The black square is on ____\"",
      "Completing the crossword: \"Write the names of the 3 computer components.\" \"It is now time to fill in the boxes with the appropriate letters for each of the computer components listed on the grid on the right.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-03",
    slug: "writing-algorithms-beginner-level",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 3,
    title: "Writing Algorithms — Beginner Level",
    description: "Meet the cat, the food plate and the four command cards on a 10x10 grid: finish a path the book has started, then write two complete programs that steer the cat around blue barrier squares it cannot cross.",
    objectives: [
      "Objectives of the lesson : Writing algorithms (beginner level)",
      "Revision: \"Let us remember what we learned in the previous lessons. A computer is made up of two parts: The Hardware (mouse, keyboard, etc.) and the Software (Paint, Scratch, etc.)\" — \"Name some computer components you can touch:\"",
      "Software: \"On a computer, you can install several software. A computer software is used for specific tasks: The Paint program is used to ____ The WordPad program is used to ____ The Scratch program is used to ____\"",
      "Algorithms: \"An algorithm is used to understand how a computer program works. Imagine you want to move the cat to reach the food plate. The movements that the cat can perform are:\"",
      "\"The cat has the right to perform the following movements:\" Move forward / Move backward / Turn right / Turn left",
      "\"In order for the cat to get to the food plate, it must perform the following movements:\" — four forward arrows and a turn-left card are printed, two boxes are empty — \"Add the two movements the cat must make to get to its plate.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-04",
    slug: "writing-algorithms-intermediate-level",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 4,
    title: "Writing Algorithms — Intermediate Level",
    description: "New cards carry a number, so the cat can move one, two or three squares at once; the child first traces a given program on a lettered 7x7 board and names the square it ends on, then writes two programs on 10x10 boards with coloured barriers.",
    objectives: [
      "Objectives of the lesson : Writing algorithms (intermediate level)",
      "1, 2 or 3 steps!: \"This exercise allows you to move the cat performing one, two or three steps.\" — three demonstration strips showing the arrow card \"1 step forward\", \"2 steps forward\", \"3 steps forward\" and the distance each one covers",
      "Exercise (1): \"The commands the cat can execute are:\" Move a step forward / Move 2 steps forward / Move 3 steps forward / Turn left / Turn right",
      "\"Determines the cat's position after executing the following commands:\" — turn left, 3 forward, 2 forward, turn right, 3 forward — \"The cat is at position : ______\"",
      "Exercise (2): \"Use the below blocks to make the cat reach the plate. The coloured squares are barriers the cat cannot cross.\"",
      "Exercise (3): \"To make the cat reach the plate, it must perform the following movements:\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-05",
    slug: "writing-algorithms-advanced-level-and-drawing-a-",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 5,
    title: "Writing Algorithms (Advanced Level) and Drawing a Square",
    description: "The board now holds numbered point squares, and the cat must reach its food collecting as many points as possible without using more moves than there are printed boxes; then, with plain up-down-left-right arrows, the cat walks a square by repeating one set of moves four times.",
    objectives: [
      "Objectives of the lesson : Writing algorithms (Advanced level) - Writing algorithm to draw a square",
      "An advanced mission: \"In this lesson, you learn how to move the cat to collect points.\"",
      "\"Use the blocks below to make the cat reach its food while collecting the maximum points.\" Move a step forward / Move 2 steps forward / Turn left / Turn right",
      "\"The number of moves must not exceed the number of the boxes below.\"",
      "\"To make the cat reach its food, it must perform the following movements:\" — \"The number of points collected: ______\"",
      "Even more!: \"Use the blocks below to make the cat reach its food while collecting the maximum points.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-06",
    slug: "writing-algorithms-with-choice-selection",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 6,
    title: "Writing Algorithms with Choice Selection",
    description: "A monkey replaces the cat and there are three numbered plates instead of one: first the program is given and the child says which plate it lands on, then the child writes programs that visit plate 1 and then plate 2, and plate 2 and then plate 3.",
    objectives: [
      "Objectives of the lesson : Writing algorithms (Advanced level) - Writing algorithms with choice selection",
      "A choice to make: \"Through this lesson, you learn to determine the path of the monkey to reach its plate.\"",
      "\"The movements the monkey can perform are as follows:\" ↑ ↓ → ←",
      "\"In order for the monkey to reach its plate, it will execute the following commands:\" — fourteen cards are printed in full",
      "\"Determine the number of the plate the monkey chose: ______\"",
      "Which plate to choose?: the same question with seven cards given and the rest left blank",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-07",
    slug: "a-complex-mission-and-meeting-blockly-games",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 7,
    title: "A Complex Mission, and Meeting Blockly Games",
    description: "Two characters share one board — Adam walking to a car and a bee flying to a balloon — and the child writes a separate program for each and counts its moves; the second page opens blockly.games in a browser and names the three activities for this year.",
    objectives: [
      "Objectives of the lesson : Writing algorithm (complex mission) - Creating an algorithm with «Blockly Games»",
      "Two paths to follow: \"Through this lesson, you learn to define two different paths to make Adam reach the car and the bee reach the balloon.\"",
      "\"The moves Adam and the Bee can perform are as follows:\" ↑ ↓ → ←",
      "\"In order to reach the car, Adam must perform the following movements:\" — \"Determine the number of moves Adam performs: ______\"",
      "\"In order to join the balloon, the Bee must perform the following movements:\" — \"Determine the number of moves the Bee performs: ______\"",
      "Blockly Games: \"Use the Blockly Games program to develop skills in coding.\" \"To get started with Blockly Games, follow the steps below:\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-08",
    slug: "introducing-loops-with-blockly-games",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 8,
    title: "Introducing Loops with Blockly Games",
    description: "Play Blockly Games Maze levels 1 to 5: move the robot to its marker, then use the \"repeat until\" block to climb a staircase, and finally solve a level under a four-block budget by combining three moves with one repeat.",
    objectives: [
      "Objectives of the lesson : Introducing the loops with «Blockly Games»",
      "Programming a robot: \"By choosing the Maze from the Blockly Games, you learn how to move the robot to reach its target. By practising the first and second levels of the game, you will acquire the skill of making the robot move.\" 1 The robot 2 The goal",
      "The robot repeating the commands: \"The third level of the game allows you to use the block «Repeat until».\"",
      "\"The block [repeat until / do] Allows you to repeat the blocks that are inside.\"",
      "\"Write down the blocks that must be placed inside the «repeat until» block for the robot to reach its goal.\"",
      "The robot climbing the stairs: \"Level 4 allows to make the robot climb the stairs.\" \"Use the block [repeat until / do]\" \"Insert the blocks that allow the robot to reach its goal by climbing the stairs.\" \"Write the blocks that allow the robot to reach its goal.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-al-09",
    slug: "creating-a-condition-in-an-algorithm",
    gradeId: "g2",
    unitId: "g2-algorithms",
    order: 9,
    title: "Creating a Condition in an Algorithm",
    description: "Blockly Games Maze levels 6 and 7 introduce the \"if path\" block, so the robot decides at a junction instead of being told, and the child solves level 6 within four blocks and writes down the steps chosen for level 7.",
    objectives: [
      "Objectives of the lesson : Creating a condition in an algorithm - Practising the condition with «Blockly Games»",
      "Exercise: \"On level 6 of the game, collect the blocks that allow the robot to reach its goal using only four blocks.\"",
      "The «if path» block: \"On level 6 of the game, collect the blocks that allow the robot to reach its goal using only four blocks.\" (the book prints this instruction twice, once under each heading)",
      "The level 6 screenshot carries the game's own hint: \"An 'if' block will do something only if the condition is true. Try turning left if there is a path to the left.\"",
      "Choosing the right path: \"Choose the right path for the robot to reach its goal.\" — the level 7 screenshot carries the hint \"Click on ahead in the 'if' block to change its condition.\"",
      "\"Write down the steps you chose.\"",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g2-ch4 — scratchjrLessons
// ------------------------------------------------------------------------

export const scratchjrChapterSummary: string =
  "\"Learn Coding With Scratch Jr\" is ten lessons on printed pages 43-62 that take a seven-year-old from a one-page revision of Grade 1's eight blue Action blocks to multi-sprite projects driven by triggers, sound and loops. The child re-reads sprite positions on the 20 x 15 ScratchJr grid, then builds five guided projects with a social theme — a duck swimming in a clean sea, a fish asking us not to dirty the water, Eric and Lea dancing in a garden, a basketball bouncing in a court, and a class chanting \"I love recycling\" three times — before inventing a story of their own and reviewing every block learned. All the new blocks are wordless picture blocks: the yellow Tap and Bump triggers, the orange Set Speed and Wait, the green Sound, the red End and Repeat Forever, and the orange counted Repeat.";

export const scratchjrLessons: Lesson[] = [
  {
    id: "g2-sc-01",
    slug: "discovering-the-scratch-junior-program",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 1,
    title: "Discovering the Scratch Junior Program",
    description: "A one-lesson revision of Grade 1: name the ScratchJr icon, the Welcome Screen buttons, the Stage and the Sprite, then fill in the missing word beside each of the eight blue Action blocks and run a five-block script.",
    objectives: [
      "Objectives of the lesson: Discovering the Scratch Junior program - Identifying the welcome screen of Scratch Jr",
      "Let us start coding!: \"Last year, in Grade 1, you learned to create projects with Scratch Junior. This year, you will learn advanced functions to develop new skills.\"",
      "A reminder from last year: \"For a good start, let us review the skills acquired last year.\"",
      "Identify the Scratch Junior program icon.",
      "Run Scratch Junior then identify the items below: To open an existing project, click on ____ / To return to the home screen, click on ____ / To create a new project, click on ____",
      "On the home screen, you can identify the Stage and the Sprite. Mark the Stage with 1. Mark the Sprite with 2.",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-02",
    slug: "changing-the-background-image-and-adding-a-new-s",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 2,
    title: "Changing the Background Image and Adding a New Sprite",
    description: "Use the plus button to open the Sprite library and add a butterfly beside Tic, then open the Scene chooser, pick a background, confirm with the blue tick, and program the Sprite to move left then right on it.",
    objectives: [
      "Objectives of the lesson: Changing the Background image of the scene - Adding a new Sprite",
      "Adding a new Sprite: \"With Scratch Junior, you can add a new Sprite to create a story or a game.\"",
      "Examine the Sprite on the screen. — Click on [+] to add a new Sprite. — All the Sprites appear on the screen. — Examine the Butterfly that appears on the stage.",
      "Choosing an image for the scene: \"Scratch Junior allows you to change the image of the scene to create attractive games and stories.\"",
      "Click on [scene icon] to choose an image for the scene. — Examine the images of the scene. — Choose an image for your project. — Click on [tick]. — Examine how the image is placed on the Stage.",
      "Time for practice: \"Launch Scratch Junior and select a Background image and a Sprite of your choice. Create the mission in order to let the Sprite move to the left then to the right.\"",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-03",
    slug: "making-the-sprite-move-in-all-directions",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 3,
    title: "Making the Sprite Move in All Directions",
    description: "Switch the ScratchJr grid on, read the Sprite's position as a pair of numbers, then trace six printed green-flag scripts across 20 x 15 grids to say where the cat lands — and, on the last two, invent the blocks that reach a marked square.",
    objectives: [
      "Objective of the lesson: Making the sprite move in all directions",
      "The Sprite in action: \"The Sprite can move on the Stage in four directions.\"",
      "Enable the Grid: Click on the Grid. — Determine the position of the Sprite. — The Sprite is on the position: ( ____ , ____ )",
      "Exercise: Determine the position of the Sprite after executing the following blocks",
      "Determine the position of the Sprite following the missions below",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-04",
    slug: "a-duck-in-the-sea-keep-the-sea-clean",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 4,
    title: "A Duck in the Sea (Keep the Sea Clean)",
    description: "A three-step guided project: put the sea background on the Stage, swap Tic for the Duck sprite by holding it for two seconds and pressing the red X, then build green flag + set speed + move right 12 + end so the duck swims across.",
    objectives: [
      "Objective of the lesson: Creating a guided project with Scratch Jr: Keep the sea clean",
      "A Duck in the sea!: \"In this lesson, you will perform the steps that allow the Duck to swim in the sea.\"",
      "The stages of the project: \"To complete the project, you must complete 3 steps:\" Place the photo of the sea on the Stage. — Add the sprite Duck. — Create the Script to make the Duck swim.",
      "Changing the Background image: Click the \"Scene\". — Select the \"sea\". — Click on \"OK\".",
      "Adding a new Sprite: Click on the \"Add new Sprite\" icon. — Select the Duck. — Click on \"OK\". — Click on the \"Tic\" for 2 seconds. — Click on X to delete the Sprite.",
      "Creating the Script: \"In order to make the Duck swim, reproduce the following Script\"",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-05",
    slug: "protecting-fish",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 5,
    title: "Protecting Fish",
    description: "Circle the sea animals among ten pictures, set the underwater scene, swap in the Fish sprite, then build a tap-triggered script that swims the fish right, turns, swims left, turns and ends with a purple Say block asking us to keep the sea clean.",
    objectives: [
      "Objective of the lesson: Creating a guided project with Scratch Jr: Protecting fish",
      "Life in the sea: Write what you can find in the sea.",
      "What do you find in the sea? Circle the animals you find in the sea.",
      "Changing the Background picture: Click on Scene. — Select the Sea Scene. — Click on OK.",
      "Changing the Sprite: Click on \"Add new sprite\". — Select the Fish Sprite. — Click on \"OK\". — Click on \"Tic\" for 2 seconds. — Click on X to delete the Sprite.",
      "Creating the Script: \"To make the fish swim in both directions, reproduce the following Script\"",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-06",
    slug: "dancing-a-sign-of-joy",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 6,
    title: "Dancing, a Sign of Joy",
    description: "Two sprites with their own scripts: Eric loops pop music and dances on the green flag, while Lea only starts dancing when Eric bumps into her — the chapter's first use of a trigger other than the flag and of Repeat Forever.",
    objectives: [
      "Objectives of the lesson: Creating a guided project with Scratch Jr: Dancing, a sign of joy",
      "Dancing together: Show how you dance with your classmates.",
      "Dancing with your classmates: Click on [sound icon] to add music to your project. — Add [pop] to play pop music.",
      "How do we dance?: \"ERIC starts dancing on a musical note. He moves to the right while jumping.\" \"When he approaches LEA, she begins to dance.\"",
      "Changing the Background picture: Click on \"Scene\". — Select the \"Garden\" Scene. — Click on \"OK\".",
      "Friends on stage: \"To add the two friends ERIC and LEA, proceed as follows:\" Click on \"Add new Sprite\". — Select the two sprites. — Click on \"OK\". — Click on the \"Tic\" sprite for 2 seconds. — Click on X to delete the Sprite.",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-07",
    slug: "sport-is-good-for-your-health",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 7,
    title: "Sport Is Good for Your Health",
    description: "Build a bouncing basketball with the red Repeat Forever block on a court background, then give the player a left-right script with Set Speed and Go Home, and finish with a free moon project where a spaceship flies and a star says \"Welcome to the moon\".",
    objectives: [
      "Objectives of the lesson: Repeating an action - Guided project: Sport is good for your health",
      "Sport is good for your health: \"In this lesson, you will learn to repeat actions.\"",
      "Choose the \"Basketball Court\" as a picture for the Background. — Choose the \"Player\" sprite. — Choose the \"Ball\" sprite.",
      "The Script to make the ball bounce: \"It's time to find out how to make the ball bounce.\" Build the mission below:",
      "The green flag to start the mission / Return to the starting point / Jump up / Jump down / Repeat blocks",
      "To the left and to the right: \"It's time to make the player move left and right.\" Assemble the blocks to get the player into action.",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-08",
    slug: "let-s-protect-the-environment",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 8,
    title: "Let's Protect the Environment",
    description: "The end-of-chapter project: a classroom scene where a teacher and two pupils chant \"I love recycling\" — introducing the orange Wait clock and the orange counted Repeat block, then asking the child to change the count from 3 to 5.",
    objectives: [
      "Objectives of the lesson: Repeating an action a specific number of times - Guided project: let's protect the environment",
      "End of chapter project: \"In this lesson, you will learn how to repeat an action a certain number of times.\"",
      "Choose the \"class room\" scene. — Choose the \"Professor\" Sprite. — Choose two \"Student\" Sprites.",
      "Let's protect the environment: \"Each student must repeat the sentence a certain number of times.\" Group the following blocks. — The teacher asks the students to repeat the sentence 3 times. — Group the following blocks.",
      "I repeat 3 times: I love recycling",
      "The student repeats the sentence 3 times: \"The Repeat block allows the blocks that are inside to be repeated a certain number of times.\"",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-09",
    slug: "creating-a-story-with-scratch-jr",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 9,
    title: "Creating a Story with Scratch Jr",
    description: "Turn a printed seven-line story about a child waking up into a ScratchJr script with Say and Wait blocks, trace a second story on the grid to find where TAC ends up, then match four rotation amounts (1, 3, 6, 9) to four pictures of a tilted plane.",
    objectives: [
      "Objective of the lesson: Creating a story with Scratch Jr",
      "Let us invent a story: \"From this lesson, we will read a story and put it on stage in Scratch Junior.\"",
      "Choose the Background image: Bedroom. — Choose the Sprite Child. — Read the story below, then reproduce it on Scratch Junior.",
      "Reading the story (1): \"The child wakes up early in the morning. He gets out of bed. He says «good morning» within five seconds. He goes to the window to check the weather. He says, «It's sunny» for five seconds. He goes to the library to choose a book. He says, 'Reading is useful,' within five seconds.\"",
      "Reading the story (2): Locate the TAC sprite at the beginning of the story. ( ____ ) — TAC moves five steps to the left. — TAC goes down three steps. — TAC moves four steps to the right. — TAC goes down seven steps. — Locate TAC at the end of the story. ( ____ )",
      "Rotation in all directions: \"In the following exercise, you learn to rotate Sprites in all directions.\" Add the «Espace» image on the Background. — Add the Sprite «Pilote».",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-sc-10",
    slug: "reviewing-the-notions-acquired-in-scratch-jr",
    gradeId: "g2",
    unitId: "g2-scratchjr",
    order: 10,
    title: "Reviewing the Notions Acquired in Scratch Jr",
    description: "Write in words what five picture blocks do — green flag, Go Home, up 2, down 2 and Repeat Forever — then build the closing project: a child cycling through a city scene, and list the health and environmental benefits of cycling.",
    objectives: [
      "Objective of the lesson: Reviewing the notions acquired in Scratch Jr",
      "Let us remember some blocks: List the function of each of the following blocks: 1 ____ 2 ____ 3 ____ 4 ____ 5 ____",
      "Let's reduce air pollution: Create the following project:",
      "The Scene image: City.",
      "The Sprite: A child on a bicycle.",
      "Create the mission that allows the Sprite to move on his bike in all directions.",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g2-ch5 — roboticsLessons
// ------------------------------------------------------------------------

export const roboticsChapterSummary: string =
  "Chapter 5 is nine lessons across printed pages 64 to 80 that carry a seven-year-old from \"what is a robot\" to writing real mBlock programs for a physical Makeblock mBot2. The first three lessons are pencil-and-Paint work: photographs of robots building cars, watering fields and cleaning floors; drawing a favourite robot; and naming the mBot2's motor, wheel, chassis and CyberPi \"memory\". From lesson 4 onward the child launches mBlock, adds the mBot2 extension, connects the robot over a USB cable, and builds missions that drive it across a floor map measured in centimetres while lighting its five LEDs, printing messages on its screen, playing notes, recording and replaying a voice, reacting to the joystick and the A/B buttons, repeating blocks, and finally responding to the tilt sensor on a ramp.";

export const roboticsLessons: Lesson[] = [
  {
    id: "g2-ro-01",
    slug: "introducing-the-science-of-robotics",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 1,
    title: "Introducing the Science of Robotics",
    description: "Read what a robot is, who made it and where robots are found, add your own examples on the ruled lines, then choose one of six cartoon robots to draw and colour and redraw a factory robot arm out of geometric shapes in Paint.",
    objectives: [
      "Objectives of the lesson : Introducing the science of robotics - Defining tasks that a robot can perform",
      "Robot : The definition — \"The robot is a machine that performs specific actions to help humans. Robots can build a car, help with farming or clean a house.\"",
      "Who invented the robot? — \"The robot is a man-made machine.\" \"The robot is made of metal, ______\"",
      "Where robots are found? — \"The robot is in the factory, in the agricultural field or in the house.\" \"The robot is also found in: ______\"",
      "What tasks can a robot perform? — \"The robot can help us pick vegetables, clean the house or make cars.\" \"The robot can also: ______\"",
      "Drawing a robot — \"Choose your favourite robot from the 6 proposed below, then draw it and colour it.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-02",
    slug: "identifying-the-different-shapes-of-a-robot",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 2,
    title: "Identifying the Different Shapes of a Robot",
    description: "Answer the three recall questions from lesson 1, pick a favourite from eight photographs of school robots and redraw it, then match an exploded mBot2 to an assembled one and name the motor and the wheel that make a robot move.",
    objectives: [
      "Objectives of the lesson : Identifying the different shapes of a robot - Identifying the parts of a robot",
      "Reminder of the previous lesson — \"In the previous lesson we learned the following.\" \"Who invented the robot?\" \"Where is a robot found?\" \"What tasks can the robot perform?\"",
      "Robots come in many shapes — \"At school, you are introduced to several forms of robots. Which one is your favourite?\"",
      "Drawing a robot — \"Redesign your favourite robot.\"",
      "The Robot parts — \"The robot is made up of several parts. Examine the two pictures and try to connect the similar parts.\"",
      "The Robot moves — \"Name the visible parts of the robot:\" \"To make a robot move, it needs a motor and a wheel.\" \"The motor can rotate forward or backward.\" \"The motor can run at several speeds.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-03",
    slug: "introducing-the-mbot2-robot",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 3,
    title: "Introducing the Mbot2 Robot",
    description: "Recall that a robot needs a motor and a wheel, learn that the skeleton or chassis holds every part together, answer four yes/no questions about what the robot can do, then meet the CyberPi as the robot's memory and see a Scratch Junior sprite next to an mBlock program that moves the robot 100 cm forward.",
    objectives: [
      "Objectives of the lesson : Introducing the Mbot2 robot - Identifying the robot skeleton - Identifying the robot brain",
      "What have you learned so far? — \"In the previous lesson, we learned the following:\" \"For a robot to move, it needs: ______\" \"What are the motor characteristics? (refer to the previous page).\"",
      "The skeleton of the robot — \"The skeleton (or chassis) of the robot includes all the parts that make up the robot. It can be metal, cardboard or plastic.\" \"The skeleton of the robot.\" \"All parts of the robot are attached to the skeleton.\"",
      "Exercise — \"Can the robot move without touching the wall? Yes / No\" \"Can the robot stop when it reaches a red line? Yes / No\" \"Can the robot produce sound or music? Yes / No\" \"Does the robot have a memory that allows it to save missions? Yes / No\"",
      "The robot's memory — \"The robot has a memory used to save the missions to be accomplished.\" \"Gives examples of missions the robot can perform:\"",
      "Programming the Sprite — \"With Scratch Junior, you learned to program the Sprite.\" \"The Sprite.\" \"The mission.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-04",
    slug: "introducing-mblock-software",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 4,
    title: "Introducing Mblock Software",
    description: "Follow seven numbered steps to launch mBlock, set the language to English, open the extension centre, add the mBot2 extension and find the mBot2 Chassis block category, then turn the robot on, plug in the USB cable, click Connect twice and run the first two-block mission.",
    objectives: [
      "Objectives of the lesson : Introducing Mblock software - Adding mBot2 robot to Mblock software - Connecting the mBot2 robot to computer",
      "Introducing mBlock software — \"mBlock allows you to create robotic missions on the mBot2 robot.\" \"To start programming the robot, follow these steps:\"",
      "\"Launch mBlock\" / \"Click on [globe]\" / \"Change language in case it is not set to English.\" / \"Click on [extension]\" / \"Click on [mbot2 shield] To add the mBot2 robot\" / \"Examine the category [mBot2 Chassis]\" / \"Using the blocks in this category, you can create a robotic mission to make the mBot2 robot move.\"",
      "Connecting the robot to the computer — \"After examining the welcome screen of the mBlock program, it is time to connect the mBot2 robot to the computer so that it can carry out the required missions.\" \"The steps followed to connect the robot to the computer are:\"",
      "\"Turn on the robot and then connect it to the computer using the USB cable.\" / \"Click on [Connect]\" / \"Click on [Connect]\"",
      "Creating a task for the robot — \"Create the robotic mission.\" \"Double click on the first block and observe the behaviour of the robot.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-05",
    slug: "programming-the-robot-to-perform-movements",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 5,
    title: "Programming the Robot to Perform Movements",
    description: "Open the movement dropdown to choose forward, backward, turn left or turn right and set an RPM speed and a duration, write a four-step mission that walks the robot round a 50-20-50-40 cm map to the END point, then light the five CyberPi lamps with an LED animation or a chosen colour.",
    objectives: [
      "Objectives of the lesson : Programming the robot to perform movements - Controlling the lights of the mBot2 robot",
      "The robot moves in all directions — \"In the previous lesson, you learned how the robot can move forward and turn left.\" \"Remember the task from the previous lesson.\" \"How to modify the movement of the robot?\" \"Click on the arrow to select:\"",
      "\"The robot moves forward.\" \"The robot moves backward.\" \"The robot turns left.\" \"The robot turns right.\" \"Set the speed of the robot.\" \"Set the duration of the movement.\"",
      "A Robot mission — \"Create a mission for the robot to reach the end point.\"",
      "Lighting up the robot lamps — \"The mBot2 robot is equipped with five lights that can be controlled like a traffic lights.\" \"The five lamps of the robot are blue.\" \"To control the lighting of the lamps, follow the steps below:\"",
      "\"Click on [LED]\" \"Use the block [play LED animation rainbow until done]\" \"Choose the lighting pattern.\" \"Use the block [display ■■■■■]\" \"Click on one of the lamps to change its colour.\" \"Change the colours of the lamps by selecting the appropriate colour.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-06",
    slug: "displaying-messages-on-the-robot-s-screen",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 6,
    title: "Displaying Messages on the Robot's Screen",
    description: "Explore the Display blocks that print HELLO on the CyberPi screen, set the text size and brush colour and clear the screen, drive the robot round a Point A - Point B - Point C - END map changing the lamp colour and printed message at each corner, then make it play sounds and single notes from the Audio category.",
    objectives: [
      "Objectives of the lesson : Displaying messages on the robot's screen - Making the robot play musical notes",
      "Displaying messages on the screen of the robot — \"In the previous lesson, we learned how to control the lighting of the robot lamps.\" \"In this lesson, we will explore how messages can be displayed on a robot's screen.\"",
      "\"Click on the category [Display]\" \"Let us explore some blocks under the Display category.\" \"[print HELLO and move to a newline] displays 'HELLO' on the robot screen.\" \"[set print size to middle] sets text size (small - middle - large).\" \"[set brush color ●]\" \"[clear screen]\"",
      "The robot plays music — \"The mBot2 robot is equipped with a speaker that allows the production of different notes and sounds.\" \"The speakers.\" \"To control the musical tones, proceed as follows:\"",
      "\"Click on [Audio]\" \"Use the block [play hi until done]\" \"Choose a sound.\" \"Use the block to play a single note.\" \"Multiple blocks can be combined to produce multiple notes.\" \"Click on the key field to select another note.\"",
      "Creating a task for the robot — \"The robot moves at a speed of 20 over a distance of 30 centimetres.\" \"All the lights are red.\" \"The robot produces several musical notes.\" \"Turns on all red lights then move backwards for 5 seconds.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-07",
    slug: "allowing-the-robot-to-record-voice-messages",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 7,
    title: "Allowing the Robot to Record Voice Messages",
    description: "Use the start recording, stop recording and play recording blocks to store two spoken sentences in the robot, play each one back with a lamp colour and a screen message as the robot reaches Point A and the goal, then drive the robot live by pushing the CyberPi joystick in four directions.",
    objectives: [
      "Objectives of the lesson : Allowing the robot to record voice messages",
      "Voice recording — \"In the previous lesson, we learned how the mBot2 robot can produce sounds and musical notes.\" \"In this lesson, we will explore how a sound can be recorded and then played through the robot's speaker.\"",
      "\"Click on [Audio]\" \"Discover some recording blocks\" \"The block [start recording] records audio.\" \"The block [stop recording] stops recording.\" \"The block [play recording] allows the robot to play the recording.\"",
      "Controlling the robot with the joystick — \"The mBot2 robot is equipped with a joystick to control the different actions of the robot.\" \"The joystick.\" \"To control the robot with the joystick, follow the steps below:\" \"Click on [Events]\" \"Use the block [when joystick pulled↑]\" \"The joystick can be pushed in four directions.\" \"If you click on forward\" \"If you click on backwards\"",
      "Creating a robotic mission — \"When you push the joystick forward, the robot moves forward for 3 seconds at a speed of 20.\" \"When you push the joystick backward, the robot moves backwards for 4 seconds at a speed of 10.\" \"When you push the joystick to the right, the robot turns 90 degrees to the right.\" \"When you push the joystick to the left, the robot turns 90 degrees to the left.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-08",
    slug: "controlling-the-mbot2-using-the-joystick",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 8,
    title: "Controlling the mBot2 Using the Joystick",
    description: "Find the A and B buttons on the CyberPi, hang missions off \"when button A pressed\" and \"when button B pressed\", read two given stacks and say what each does, then wrap blocks inside the repeat and forever blocks from the Control category.",
    objectives: [
      "Objectives of the lesson : Controlling the mBot2 using the joystick - Introducing the \"Repeat\" block in a robotics mission",
      "The control buttons A and B — \"In the previous lesson, we learned how to perform robotic missions using the Joystick.\" \"Examine the robot joystick to control missions.\" \"In this lesson, we will learn how to perform tasks with A-B buttons.\" \"The A button\" \"The B button\"",
      "\"Click on [Events]\" \"[when button A pressed] Allows the robot to perform a mission when the Button A is pressed.\" \"Click on the arrow to choose Button B.\"",
      "Exercise — \"Define the function of each of the following two tasks:\"",
      "Repeating a robotics mission — \"The mBot2 robot can repeat a mission several times.\" \"From the category [Control] the repeat block can be added\" \"Repeat a certain number of times.\" \"The Forever repeat block.\"",
      "Exercise — \"Create the following two missions, then explain their functions.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g2-ro-09",
    slug: "programming-the-robot-with-the-tilt-sensor",
    gradeId: "g2",
    unitId: "g2-robotics",
    order: 9,
    title: "Programming the Robot with the Tilt Sensor",
    description: "Meet the CyberPi motion sensor that detects which way the robot is leaning, read four tilt missions and describe how the robot behaves, then place the real robot on a ramp so that tilting forward drives it forward and tilting backward drives it back.",
    objectives: [
      "Objectives of the lesson : Programming the robot with the tilt sensor",
      "The robot performs a mission by detecting tilts — \"The mBot2 robot is equipped with a motion sensor. It can detect the tilt direction.\"",
      "\"The robot detects tilts when it leans to the left.\" \"The robot detects tilts when it leans to the right.\" \"The robot detects tilts when it leans forward.\" \"The robot detects tilts when it leans back.\"",
      "\"Examine the four missions and then describe the behaviour of the robot when it detects tilts in the different directions.\"",
      "Mission to execute — \"Place the robot on a ramp and create the following two tasks, then write the results you get.\"",
    ],
    skillIds: ["rob-build", "prog-blocks"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Bot",
    status: "coming-soon",
    stages: [],
  },
];
