import type { BadgeDef } from "@/types/content";

export const BADGES: BadgeDef[] = [
  {
    id: "first-boot",
    title: "First Boot",
    description: "Complete your first ZERO1 mission.",
    tier: "bronze",
    icon: "Power",
    rule: { type: "lessons-count", count: 1 },
  },
  {
    id: "binary-master",
    title: "Binary Master",
    description: "Complete the Binary Numbers mission.",
    tier: "gold",
    icon: "Binary",
    rule: { type: "lesson-complete", lessonId: "g6-idw-binary" },
  },
  {
    id: "system-builder",
    title: "System Builder",
    description: "Complete the Computer Systems mission.",
    tier: "silver",
    icon: "Cpu",
    rule: { type: "lesson-complete", lessonId: "g6-idw-systems" },
  },
  {
    id: "algorithm-explorer",
    title: "Algorithm Explorer",
    description: "Complete the Algorithms mission.",
    tier: "silver",
    icon: "GitBranch",
    rule: { type: "lesson-complete", lessonId: "g6-idw-algorithms" },
  },
  {
    id: "network-engineer",
    title: "Network Engineer",
    description: "Complete the Networks mission.",
    tier: "silver",
    icon: "Network",
    rule: { type: "lesson-complete", lessonId: "g6-idw-networks" },
  },
  {
    id: "cyber-defender",
    title: "Cyber Defender",
    description: "Complete the Cybersecurity mission.",
    tier: "gold",
    icon: "ShieldCheck",
    rule: { type: "lesson-complete", lessonId: "g6-idw-cyber" },
  },
  {
    id: "digital-world-champion",
    title: "Digital World Champion",
    description: "Complete every mission in Inside the Digital World.",
    tier: "gold",
    icon: "Trophy",
    rule: { type: "unit-complete", unitId: "g6-idw" },
  },
  {
    id: "sharp-mind",
    title: "Sharp Mind",
    description: "Pass 3 checkpoints with a perfect score.",
    tier: "silver",
    icon: "Target",
    rule: { type: "perfect-checkpoint", count: 3 },
  },
  {
    id: "streak-3",
    title: "Powered On",
    description: "Learn 3 days in a row.",
    tier: "bronze",
    icon: "Flame",
    rule: { type: "streak", days: 3 },
  },
  {
    id: "streak-7",
    title: "Always On",
    description: "Learn 7 days in a row.",
    tier: "silver",
    icon: "Zap",
    rule: { type: "streak", days: 7 },
  },
  {
    id: "xp-500",
    title: "Half-Kilobyte",
    description: "Earn 500 XP.",
    tier: "bronze",
    icon: "Award",
    rule: { type: "xp", amount: 500 },
  },
  {
    id: "xp-1024",
    title: "Kilobyte Club",
    description: "Earn 1,024 XP — a true kilobyte of learning.",
    tier: "gold",
    icon: "MemoryStick",
    rule: { type: "xp", amount: 1024 },
  },
];

export const badgeById = new Map(BADGES.map((b) => [b.id, b]));
