import type { BadgeDef } from "@/types/content";

export const BADGES: BadgeDef[] = [
  {
    id: "first-boot",
    title: "First Boot",
    description: "Complete your first ZERO1 mission.",
    tier: "bronze",
    icon: "Power",
    rule: { type: "lessons-count", count: 1 },
  },
  {
    id: "microcontroller-master",
    title: "Microcontroller Master",
    description: "Complete Introduction to Microcontrollers.",
    tier: "silver",
    icon: "Cpu",
    rule: { type: "lesson-complete", lessonId: "g6-mb-01" },
  },
  {
    id: "iot-explorer",
    title: "IoT Explorer",
    description: "Complete Defining Smart Objects & IOT.",
    tier: "silver",
    icon: "Wifi",
    rule: { type: "lesson-complete", lessonId: "g6-mb-02" },
  },
  {
    id: "variable-wizard",
    title: "Variable Wizard",
    description: "Build the stopwatch and master variables.",
    tier: "gold",
    icon: "Variable",
    rule: { type: "lesson-complete", lessonId: "g6-mb-04" },
  },
  {
    id: "matrix-artist",
    title: "Matrix Artist",
    description: "Light up the 25-LED matrix by its coordinates.",
    tier: "silver",
    icon: "Grid3x3",
    rule: { type: "lesson-complete", lessonId: "g6-mb-06" },
  },
  {
    id: "loop-master",
    title: "Loop Master",
    description: "Control the LEDs with variables and loops.",
    tier: "gold",
    icon: "Repeat",
    rule: { type: "lesson-complete", lessonId: "g6-mb-07" },
  },
  {
    id: "environment-guardian",
    title: "Environment Guardian",
    description: "Read the air quality station and warn the room.",
    tier: "silver",
    icon: "ThermometerSun",
    rule: { type: "lesson-complete", lessonId: "g6-mb-08" },
  },
  {
    id: "microbit-champion",
    title: "micro:bit Champion",
    description: "Complete every lesson in MakeCode for micro:bit.",
    tier: "gold",
    icon: "Trophy",
    rule: { type: "unit-complete", unitId: "g6-microbit" },
  },
  {
    id: "sharp-mind",
    title: "Sharp Mind",
    description: "Pass 3 checkpoints with a perfect score.",
    tier: "silver",
    icon: "Target",
    rule: { type: "perfect-checkpoint", count: 3 },
  },
  {
    id: "streak-3",
    title: "Powered On",
    description: "Learn 3 days in a row.",
    tier: "bronze",
    icon: "Flame",
    rule: { type: "streak", days: 3 },
  },
  {
    id: "streak-7",
    title: "Always On",
    description: "Learn 7 days in a row.",
    tier: "silver",
    icon: "Zap",
    rule: { type: "streak", days: 7 },
  },
  {
    id: "xp-500",
    title: "Half-Kilobyte",
    description: "Earn 500 XP.",
    tier: "bronze",
    icon: "Award",
    rule: { type: "xp", amount: 500 },
  },
  {
    id: "xp-1024",
    title: "Kilobyte Club",
    description: "Earn 1,024 XP — a true kilobyte of learning.",
    tier: "gold",
    icon: "MemoryStick",
    rule: { type: "xp", amount: 1024 },
  },
];

export const badgeById = new Map(BADGES.map((b) => [b.id, b]));
