import type { Lesson } from "@/types/content";

/**
 * Grade 1 — the printed 2023 edition, chapter by chapter.
 *
 * Titles, descriptions and objectives are read off the pages. Where the book
 * prints no lesson title of its own, the title is its first stated objective
 * or a heading printed on the page — never invented.
 */

// ------------------------------------------------------------------------
// g1-ch1 — introComputersLessons
// ------------------------------------------------------------------------

export const introComputersChapterSummary: string =
  "Chapter 1 is a six-year-old's first eight sittings at a computer, printed pages 4 to 18. It names only three components — the screen, the keyboard and the mouse — then spends the rest of the chapter on where computers are found (home, school, restaurant, factory, airport, pharmacy) and who uses them (students, architects, teachers, restaurant owners). Every lesson pairs its picture page with a GCompris drill: Move the mouse, Click or Tap, Click on Me, Click and draw, Numbers With Dice, Photo hunter, Maze, Draw numbers, Count the items, Number sequence, Enumeration memory game and Addition of numbers — so the child practises moving, clicking, drawing with the mouse, driving with the arrow keys, and counting.";

export const introComputersLessons: Lesson[] = [
  {
    id: "g1-in-01",
    slug: "introduce-the-computer-and-its-components",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 1,
    title: "Introduce the Computer and Its Components",
    description: "Tick who has a computer at home and what it is used for, learn that a computer is made of a screen, a keyboard and a mouse, then copy a screen and a mouse into empty boxes and meet the GCompris welcome screen.",
    objectives: [
      "Objective of lesson 1: Introduce the computer and its components",
      "Computers are everywhere: \"In this first lesson, we will learn about the functions of a computer as well as its most important components.\"",
      "Definition of a computer: \"A computer is designed by humans to accomplish a specific task.\" \"The computer is used everywhere: at home, at school, in the restaurant, in the factory, etc...\"",
      "How is a computer used? It is used to: Calculate / Draw / Watch Cartoons / Listen to music",
      "The computer's components: \"A computer is made of several parts; the most important ones are the screen, the keyboard and the mouse.\"",
      "GCOMPRIS: \"The GCOMPRIS program contains activities that help you use your computer better. One of the most important activities is how to use the mouse and the keyboard.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-02",
    slug: "know-where-computers-are-used",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 2,
    title: "Know Where Computers Are Used",
    description: "Say who invented the computer and where computers are found, then open GCompris and use \"Move the mouse\" and \"Click or Tap\" to rub the cubes off a hidden photo.",
    objectives: [
      "Objectives of lesson 2: Know where computers are used - Master the use of the computer mouse",
      "Warm up practice: Who invented the computer? The doctor / The teacher / The engineer — Mention some places where the computer is used",
      "Where is the computer used? \"Computers are used in most places and professions.\" School / Restaurant / Home / Factory",
      "GCOMPRIS: \"It's time to use the GCOMPRIS program to master the use of the computer mouse.\" Click on Move the mouse to start the activity where you practise moving the mouse — Move the mouse in all directions to erase the cubes covering the image — When you clear all the cubes, you move to a new level of the game",
      "GCOMPRIS: \"It's time to open GCOMPRIS to master the use of the computer mouse.\" Click on Click or Tap to open the activity — Click on the cubes to be erased — At the end of the activity, the entire background image appears",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-03",
    slug: "a-click-or-two",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 3,
    title: "A Click or Two?",
    description: "Learn what the mouse is for, that most jobs need one left-click and that a Desktop icon needs a double-click, then click the fish swimming past in GCompris \"Click on Me\".",
    objectives: [
      "Objective of lesson 3: Master the use of the computer mouse",
      "Definition: \"The computer mouse is one of the basic components used to:\" Run a program / Draw an illustration / Turn off the computer / Write a document",
      "A click or two?: \"To use a computer mouse correctly, learn how to click once or twice.\" \"Most of the time, you need a single left-click of the mouse in order to:\" Draw / Select a word",
      "Running a program: \"To run a program where the icon is on the Desktop of the computer, double-click on the program icon.\"",
      "Click on me!: Click on \"Click on Me\" to launch the activity that teaches you how to click on a computer mouse — Click on the fish that passes in front of you on the screen",
      "Tablet or phone!: \"Are tablets and mobile phones used for the same purpose as computers? Justify your answer.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-04",
    slug: "who-uses-a-computer",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 4,
    title: "Who Uses a Computer?",
    description: "Match jobs to the computers they use — pharmacy, school, airport, restaurant — then complete drawings in GCompris \"Click and draw\" by clicking the green circles.",
    objectives: [
      "Objective of lesson 4: Master the use of the computer mouse",
      "Who uses a computer?: \"The computer has several uses.\" Students use a computer to study, draw, write a text or listen to music / Architects use a computer to draw geometric shapes for houses / Owners of a restaurant use a computer to issue invoices to customers / Teachers use a computer to give online lessons and to prepare exercises",
      "Practice: \"Join the two halves of the sentences.\"",
      "Mastering computer mouse: Click on \"Click and draw\" to launch the activity that helps you master the click of the mouse — Click on the green circle to complete the drawing",
      "Practice: \"Summarize in a short sentence what you have learned so far: The components of a computer are… A computer is used to… A computer is found in…\"",
      "Join the dots: \"It's time to use GCOMPRIS to be able to master the click of the mouse.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-05",
    slug: "counting-numbers-and-spotting-the-differences",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 5,
    title: "Counting Numbers and Spotting the Differences",
    description: "Type the number shown on falling dice in GCompris \"Numbers With Dice\", write six sums on the page, then find the differences between two pictures with \"Photo hunter\".",
    objectives: [
      "Objectives of lesson 5: Count numbers - Compare two pictures to spot the differences",
      "Counting numbers: \"Gcompris allows you to develop skills in math.\" Launch Gcompris — Click on Numbers With Dice — Type the numbers shown on the screen",
      "\"Complete the following exercise by adding the numbers and writing their sum.\"",
      "Spotting the differences: \"Gcompris allows you to use the 'photo hunter' exercise to spot the differences between two images.\" Launch Gcompris — Click on \"photo hunter\" — Mark the differences between the two images shown in front of you",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-06",
    slug: "arrow-keys-exercise",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 6,
    title: "Arrow Keys Exercise",
    description: "Drive a penguin through a maze to the exit door with the keyboard arrow keys, write the path as arrows in an empty grid, then trace numbers by clicking blue circles in \"Draw numbers\".",
    objectives: [
      "Objective of lesson 6: Control the movement of the penguin using the keyboard arrow keys",
      "Arrow keys exercise: \"Gcompris allows you to use various activities to acquire the ability to use the arrow keys of the keyboard.\" Launch Gcompris — From the home screen, click on [the maze activity] — Use the arrow keys to guide the penguin to the exit door",
      "Connect the dots: \"The Gcompris program allows you to use the 'Draw Numbers' exercise to acquire skills in drawing numbers.\" Launch Gcompris — From the welcome screen, click on \"Draw numbers\" — Click on the blue circle to draw the number",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-07",
    slug: "fruit-count-and-sequence-of-numbers",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 7,
    title: "Fruit Count and Sequence of Numbers",
    description: "Count apples and lemons on the GCompris turtle and type the totals, then click and link the numbers 13 to 25 in the correct order.",
    objectives: [
      "Objective of lesson 7: Enumerate numbers",
      "Fruit count practice: \"The Gcompris program allows you to use various activities to be able to count objects.\" Launch Gcompris — From the welcome screen, click on Count the items — Type the number of fruits shown on the screen — Type the number of apples and lemons and apples shown on the screen",
      "Sequence of numbers: \"The Gcompis program allows you to use the 'Number Sequence' exercise to acquire the skill of enumerating the numbers correctly.\" Launch Gcompris — From the home screen, click on \"Number sequence\" activity — Click on the numbers in the correct sequence — Link the circles in the correct sequence order",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-08",
    slug: "focus-activities-and-adding-numbers",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 8,
    title: "Focus Activities and Adding Numbers",
    description: "Play the GCompris memory game by turning two cards at a time to find matching pairs, then add the numbers shown in the balloon activity and type the result.",
    objectives: [
      "Objective of lesson 8: Practice memory and math activities with Gcompris",
      "Focus activities: \"Gcompris allows you to use various activities to be able to refresh the memory.\" Launch Gcompris — From the welcome screen, click on Enumeration memory game — Click on two cards to open them. You win if the cards match — If the two cards do not match, they will be closed to try again",
      "Adding numbers: \"Gcompris allows you to use various activities to be able to practise adding numbers.\" From the welcome screen, click on [Addition of numbers] — Add the numbers displayed on the screen then type the result",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g1-ch2 — paintLessons
// ------------------------------------------------------------------------

export const paintChapterSummary: string =
  "Chapter 2 is six lessons in Microsoft Paint, printed pages 20 to 30, and it introduces the tools in a fixed order: Shapes and the rectangle, Color 1 for the outline, Color 2 with Fill > Solid color for the inside, then Brushes (Crayon, Natural pencil, Calligraphy brush 1), Size, File > Save, Select with Copy and Paste, the Pen with Fill Color, and finally Resize and skew. The shapes it names are the rectangle, triangle, oval shape, line, star and arrow. Each lesson ends with a plate to reproduce — a robot face of rectangles, a coloured shape sheet, a house and an apple tree, a duplicated house scene, a car, and closing step-by-step plates for a fish and a robot.";

export const paintLessons: Lesson[] = [
  {
    id: "g1-pa-01",
    slug: "launch-paint-and-draw-squares",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 1,
    title: "Launch Paint and Draw Squares",
    description: "Find Paint from the Start menu, look over its menu and drawing tools, then use Shapes and the rectangle in red and black to build a robot's face.",
    objectives: [
      "Objectives of lesson 1: Introduce the program Paint - Draw squares",
      "Paint to draw: \"The Paint program allows you to draw on the computer.\" Have you ever used the Paint program? Yes / No — Which icon is for the Paint program?",
      "Launch Paint: \"In order to start drawing using Paint, follow these steps:\" Click on \"Start\" — In the search field, type the word \"paint\" — Click on Paint to launch it — The welcome screen of the \"Paint\" program appears in front of you — Examine the main menu — Examine the drawing tools",
      "Practice: \"Try to launch the Paint program then close it.\"",
      "Drawing squares: \"Drawing shapes is an easy process:\" Click on \"Shapes\" — Choose the \"rectangle\" — Use your mouse to draw a rectangle — Draw a rectangle — Choose the red colour — Draw a red rectangle",
      "Practice: \"Use the rectangle to draw the robot face.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-02",
    slug: "draw-shapes-and-change-the-border-colour",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 2,
    title: "Draw Shapes and Change the Border Colour",
    description: "Name six Paint shapes, draw an arrow and a star, use Color 1 to change the outline colour and Color 2 with Fill > Solid color to change the inside colour.",
    objectives: [
      "Objectives of lesson 2: Draw shapes - Change the shape and the border colour",
      "Changing shapes: \"In this exercise, we will learn about some of the shapes that can be drawn using the 'Paint' program.\" \"Match each term with the corresponding shape.\" Triangle / Oval shape / Rectangle / Line / Star / Arrow",
      "Drawing shapes: \"To draw shapes with different colours, follow these steps:\" Click on Shapes — Choose the shape you want to draw — Check the available shapes — Draw an arrow then a star",
      "Color the shape's contour: \"If you want to draw shapes with different contour colours, follow these steps:\" Click on \"Color 1\" — Choose the color you want to use — Draw the shape you want — Notice how the contour of the arrow is green",
      "Changing the inside colour of a shape: \"It's time to learn how to change the inside colour of a shape.\" Click on \"Color 2\" — Choose the color you want — Click on Fill, then choose Solid Color — Draw the star — Look how the star is painted in yellow",
      "Practice: \"Draw the following shapes using the same colours.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-03",
    slug: "draw-with-a-brush-and-save-the-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 3,
    title: "Draw with a Brush and Save the Drawing",
    description: "Pick a brush head — Crayon, Natural pencil or Calligraphy brush 1 — change its Size, draw a house and an apple tree, then save the picture with File > Save.",
    objectives: [
      "Objectives of lesson 3: Draw shapes using a brush - Change the brush size - Save a drawing",
      "Using the brush for beautiful drawings: \"It's time to use the brush to draw new shapes.\" Select the Brush button — Choose the shape of the brush you want to use — The Crayon brush — A brush that paints in the form of a \"Natural pencil\" — Calligraphy brush 1",
      "Practice: \"Use the geometric shapes and the brush to reproduce the following drawing.\"",
      "Changing the brush size: \"To use the brush in different sizes, click on 'Size'.\" Choose the size you want then start drawing",
      "Saving the drawing: \"When you finish drawing, and before closing the 'Paint' program, you must save the drawing on your computer.\" Click on \"File\" — Click on \"Save\" — Type the file name — Click on \"Save\" — You can now exit the Paint program — \"The drawing is on your computer. You can open it again whenever you want.\"",
      "Practice: \"Use the Paint program to draw a sun and a moon, then save the drawing on your computer.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-04",
    slug: "select-and-copy-paste-a-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 4,
    title: "Select and Copy/Paste a Drawing",
    description: "Reproduce a house-and-sun picture, then use Select, Copy and Paste to duplicate the whole drawing and slide the copy to the right.",
    objectives: [
      "Objectives of lesson 4: Select a drawing - Copy/Paste a drawing",
      "Copying and Pasting: \"In this lesson, we will learn how to select a graphic in order to copy it and duplicate it.\"",
      "\"Reproduce the drawing below in the same colour.\"",
      "Click on Select — Select the drawing you want to copy — Click on Copy — Click on \"paste\" — Move the copied shape to the right",
      "Note: \"To master the use of the selection skills, watch the tutorial on the book's digital platform www.zero1.education.\"",
      "Practice: \"Redraw the fish then reproduce it on the Paint program. Save it on the computer.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-05",
    slug: "copy-paste-and-resize-a-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 5,
    title: "Copy, Paste and Resize a Drawing",
    description: "Draw a car with the Pen, colour it with Fill Color and add the wheels, then shrink it with Select and Resize and skew by percentage.",
    objectives: [
      "Objectives of lesson 5: Copy and Paste a drawing - Change the size of a drawing",
      "An image to draw: \"In this lesson, we will learn the steps to draw a car.\" Look at the shape of the car — Choose the Pen then select the size — Draw the car Skeleton — Click on \"Fill Color\" to change the colour of the car — Draw the wheels",
      "Changing the image size: \"It is time to learn how to change the size of the car by following simple steps.\" Select the graphic you want to resize — Click on \"Resize and skew\" — Select the reduction or enlargement percentage, then click on OK — Examine the result",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-06",
    slug: "drawing-a-fish-and-a-robot-with-paint",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 6,
    title: "Drawing a Fish and a Robot with Paint",
    description: "Two closing plates: build a fish in six drawing stages and a robot in three, then colour them in.",
    objectives: [
      "Objective of lesson 6: Drawing a fish and a robot with Paint",
      "An image to draw: \"Use your drawing skills to draw a fish.\"",
      "A robot to draw: \"Use your drawing skills to draw a robot.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g1-ch4 — algorithmsLessons
// ------------------------------------------------------------------------

export const algorithmsChapterSummary: string =
  "Chapter 4, 'Computer Programming: Algorithms', is where a six-year-old writes a program for the first time — on paper, then on screen. The first five lessons all use one apparatus: a 10x10 blue-lined grid holding a LEGO-style robot, a house and scattered coloured cubes, plus a palette of arrow cards (left, right, up, down, and from lesson 3 a fifth 'jump' card) that the child copies into a strip of empty boxes, seven to a row. The chapter walks that grid through five ideas — read a drawn path and write its arrow sequence, notice that a square is four arrows repeated four times, insert a jump where the path meets a cube, count points collected along the way, and finally invent a path and write its program — then moves to the screen for six software lessons: Blockly Games (Maze, Turtle with the 'repeat until' block, and the animal Puzzle) in lessons 6-8, and GCompris's 'Programming maze', where the child sequences turn-left / turn-right / move-forward instructions to get a penguin to a fish, in lessons 9-11.";

export const algorithmsLessons: Lesson[] = [
  {
    id: "g1-al-01",
    slug: "controlling-the-movement-of-the-robot",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 1,
    title: "Controlling the Movement of the Robot",
    description: "On a 10x10 grid a robot's route to its house is already drawn in ink; the child reads that route square by square and writes it out as a row of arrow cards.",
    objectives: [
      "Objective of lesson 1 : Controlling the movement of the robot",
      "In this lesson, you will learn how to move the robot to get home.",
      "Use the arrows to move the robot on the right path.",
      "To be able to reach its home, the robot must perform the following movements:",
      "It is your time to practise",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-02",
    slug: "drawing-geometrical-shapes",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 2,
    title: "Drawing Geometrical Shapes",
    description: "The robot traces a square and then rectangles on the grid, and the child writes the arrow sequence and answers how many times each movement repeats — the chapter's first look at a loop.",
    objectives: [
      "Objective of lesson 2 : Drawing geometrical shapes",
      "In this lesson, you will learn how to repeat the movements of a robot in order to draw a square.",
      "Use the arrows below to draw a square.",
      "To be able to draw a square, the robot must follow the movements below:",
      "How many times is each movement repeated? ..........",
      "Use the arrows to make the robot draw a rectangle.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-03",
    slug: "moving-the-robot-without-touching-the-obstacles",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 3,
    title: "Moving the Robot Without Touching the Obstacles",
    description: "A fifth command card appears — jump — and the child inserts it into the arrow sequence at exactly the squares where the robot's path runs into a coloured cube.",
    objectives: [
      "Objective of lesson 3 : Moving the robot without touching the obstacles",
      "In this lesson, you will learn how to move the robot with the ability to jump upon reaching a cube.",
      "Use this block to jump.",
      "Use the arrows to move the robot on the right path.",
      "To reach its home, the robot must perform the following movements:",
      "Use the blocks below to move the robot on the right path.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-04",
    slug: "moving-the-robot-to-collect-points",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 4,
    title: "Moving the Robot to Collect Points",
    description: "Small numbers now sit on the grid squares the route crosses; the child writes the arrow sequence, carries a running score on the cards, and fills in a Total points box.",
    objectives: [
      "Objective of lesson 4 : Moving the robot to collect points",
      "In this lesson, you will learn how to move the robot while collecting points on its path.",
      "Use the blocks below to move the robot on the right path.",
      "Use this block to jump.",
      "To reach its target, the robot must perform the following movements:",
      "Total points → [ ]",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-05",
    slug: "creating-a-free-path-and-make-the-robot-follow-i",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 5,
    title: "Creating a Free Path and Make the Robot Follow It",
    description: "First the child draws the path that a given block sequence produces, then invents a path of their own on an empty grid and writes the program that would produce it.",
    objectives: [
      "Objective of lesson 5 : Creating a free path and make the robot follow it",
      "In this lesson, you will learn how to move the robot to plot a path using a set of commands.",
      "Draw the path of the robot using the blocks below.",
      "Create a free path of your choice.",
      "Draw the path of the robot in the boxes below.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-06",
    slug: "learning-coding-with-the-maze-game",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 6,
    title: "Learning Coding With the Maze Game",
    description: "The chapter leaves paper for Blockly Games: open blockly.games, meet the eight games, and run the first Maze level by stacking two 'move forward' blocks.",
    objectives: [
      "Objective of lesson 6 : Learning coding with the maze game",
      "By using the \"Blockly Games\" program, you will learn how to program a computer.",
      "To get started with \"Blockly Games\", follow the steps below:",
      "Launch the internet browser.",
      "Open the website https://blockly.games",
      "The main screen of the \"Blockly Games\" program shows you eight games.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-07",
    slug: "using-the-repeat-block-to-draw-shapes",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 7,
    title: "Using the Repeat Block to Draw Shapes",
    description: "Blockly Maze levels 2 to 5: turn left and right, then discover the 'repeat until' block and write down the block stack that solves each level.",
    objectives: [
      "Objective of lesson 7 : Using the Repeat block to draw shapes",
      "The robot turns left and right",
      "Moving to a second level in the game, the robot can turn left and right.",
      "Examine the robot's path in yellow.",
      "Write the blocks that allow the robot reach the target.",
      "The robot repeats the blocks",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-08",
    slug: "using-coding-skills-to-draw-geometrical-shapes",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 8,
    title: "Using Coding Skills to Draw Geometrical Shapes",
    description: "The Blockly Turtle draws a square with eight blocks, then with a 'repeat 4 times' loop chosen from three printed candidates, and the Puzzle activity has the child record each animal's legs and traits.",
    objectives: [
      "Objective of lesson 8 : Using coding skills to draw geometrical shapes",
      "The turtle draws a square",
      "In this lesson, we will learn how to create a program to draw a square.",
      "You need eight blocks to draw a square.",
      "The block move forward by 100 allows the turtle to move forward.",
      "The block turn right by 90° allows the turtle to turn right.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-09",
    slug: "programming-the-maze-with-gcompris",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 9,
    title: "Programming the Maze With Gcompris",
    description: "Back in GCompris, the child opens the 'Programming maze' activity and sequences turn-left, turn-right and move-forward instructions to make the penguin reach the fish.",
    objectives: [
      "Objective of lesson 9 : Programming the maze with Gcompris",
      "Programming skills",
      "In the previous lessons, you learned how to develop programming skills by moving the robot to reach its target.",
      "It's time to go back to Gcompris for more computer coding exercises.",
      "Launch Gcompris. From the home screen, click on: [coding category]. From the displayed activity choose: Programming maze.",
      "There are 3 instructions which you can use to code and lead Tux to the fish: 1. Move forward: Moves Tux one step forward in the direction it is facing. 2. Turn left: Turns Tux to the left. 3. Turn right: Turns Tux to the right.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-10",
    slug: "programming-the-maze-with-gcompris",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 10,
    title: "Programming the Maze With Gcompris",
    description: "Four harder GCompris 'Programming maze' levels, each with an instruction budget printed on the screenshot, recorded as sequences in blank instruction boxes.",
    objectives: [
      "Objective of lesson 10 : Programming the maze with Gcompris",
      "Choose the correct blocks to make the penguin reach the fish.",
      "Reach the fish in less than 15 instructions.",
      "Reach the fish in less than 16 instructions.",
      "Reach the fish in less than 9 instructions.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-al-11",
    slug: "programming-a-maze",
    gradeId: "g1",
    unitId: "g1-algorithms",
    order: 11,
    title: "Programming a Maze",
    description: "A single closing page with no screenshots at all: two paper mazes drawn as chains of blank boxes between a penguin and a fish, each to be solved as a written instruction sequence.",
    objectives: [
      "Objective of lesson 11 : Programming a maze.",
      "Choose the correct blocks to make the penguin reach the fish.",
      "Choose the correct instructions to make the penguin reach the fish.",
    ],
    skillIds: ["algo-sequence", "ct-patterns"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Footprints",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g1-ch5 — scratchjrLessons
// ------------------------------------------------------------------------

export const scratchjrChapterSummary: string =
  "\"Learn Coding with Scratch Jr\" is six short lessons on printed pages 70-80 that take a six-year-old from launching ScratchJr to building a free project of their own. The child meets the Welcome Screen, the Stage, the Sprite TIC and the programming area, then works through the eight blue Action blocks, reads a Sprite's position on the ScratchJr grid, changes the Stage picture and adds Sprites, resizes two Sprites with the purple Grow and Shrink blocks, and finally makes two Sprites hold a typed conversation with Say and Wait. Every block in the chapter is a wordless picture block, and most of the paper work is reading a printed script of picture blocks and predicting where the Sprite lands.";

export const scratchjrLessons: Lesson[] = [
  {
    id: "g1-sc-01",
    slug: "introducing-the-program-scratch-junior",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 1,
    title: "Introducing the Program Scratch Junior",
    description: "Launch ScratchJr, open a new project from the Welcome Screen, name the Stage, the Sprite TIC and the programming area, then meet the eight blue Action blocks and run a first script by tapping it.",
    objectives: [
      "Introducing the program Scratch Junior",
      "Identifying the welcome screen of Scratch Junior",
      "Why Scratch Junior?: \"Scratch Junior lets you program a computer to create games and stories.\"",
      "To launch Scratch Junior, click on its icon",
      "Discover the Welcome Screen",
      "To start a new project, click on [+]",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-sc-02",
    slug: "making-the-sprite-move-in-all-directions",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 2,
    title: "Making the Sprite Move in All Directions",
    description: "Turn on the ScratchJr grid, read the Sprite's position as a pair of numbers, then trace printed scripts of blue move blocks across a 20 x 15 grid to predict where the Sprite finishes.",
    objectives: [
      "Making the Sprite move in all directions",
      "In all directions: \"The Sprite moves on the screen in all directions.\"",
      "Click on Grid",
      "Look at the position of the Sprite",
      "The position of the Sprite is ( ....... , ....... )",
      "Exercise: Determine the position of the Sprite after executing the following mission",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-sc-03",
    slug: "changing-the-picture-of-the-stage-and-adding-a-n",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 3,
    title: "Changing the Picture of the Stage and Adding a New Sprite",
    description: "Open the background chooser to give the mission a Stage picture, add a second Sprite from the Sprite library, and then build a small mission of your own choosing on that scene.",
    objectives: [
      "Changing the picture of the Stage",
      "Adding a new Sprite",
      "Choosing a Stage for your mission: \"Scratch Junior lets you change the image of the Stage to create entertaining games and stories.\"",
      "Click on the icon to choose a new image for the Stage",
      "Examine the available images for the Stage",
      "Choose an image",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-sc-04",
    slug: "animating-two-sprites",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 4,
    title: "Animating Two Sprites",
    description: "Put a frog and a butterfly on a forest background, then use the purple Grow and Shrink blocks under a green flag so both Sprites change size when the flag is clicked.",
    objectives: [
      "Animating two Sprites",
      "Meeting the Butterfly and the Frog: \"In this lesson, you will learn how to animate two sprites on the same background.\"",
      "Step one: add a background image representing the forest",
      "Step two: add the two sprites, the frog and the butterfly",
      "To modify the size of the sprites, proceed as follows",
      "To increase the size of the Sprite, add the block [Grow]",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-sc-05",
    slug: "creating-a-dialogue-between-two-sprites",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 5,
    title: "Creating a Dialogue Between Two Sprites",
    description: "Give each of the two Sprites a Say block with a typed sentence and a Wait block between the turns, so that clicking the green flag plays a conversation on the Stage.",
    objectives: [
      "Creating a dialogue between two Sprites",
      "The Sprite talking: \"It is time to create a dialogue between the Sprites.\"",
      "Remember the exercise from the previous lesson",
      "The picture of the Stage",
      "The two Sprites TAC and TOC",
      "Everything is ready to start the dialogue between the two Sprites",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-sc-06",
    slug: "creating-free-projects-with-scratch-junior",
    gradeId: "g1",
    unitId: "g1-scratchjr",
    order: 6,
    title: "Creating Free Projects with Scratch Junior",
    description: "Two open-ended builds with the teacher — a ScratchJr project in which a Sprite tells a story, and one in which two Sprites dance on the Stage — with the steps written down on the printed lines.",
    objectives: [
      "Creating free projects with Scratch Junior",
      "The Sprite telling a story: \"With the help of your teacher, create the Scratch Junior project where the Sprite tells a story.\" — The steps to follow: (6 blank lines)",
      "The Sprites dancing on the Stage: \"With the help of your teacher, create the Scratch Junior project where two Sprites dance on the stage.\" — The steps to follow: (6 blank lines)",
    ],
    skillIds: ["prog-blocks", "algo-sequence"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Cat",
    status: "coming-soon",
    stages: [],
  },
];
