import type { Lesson } from "@/types/content";

/**
 * Grade 1 — the printed 2023 edition, chapter by chapter.
 *
 * Titles, descriptions and objectives are read off the pages. Where the book
 * prints no lesson title of its own, the title is its first stated objective
 * or a heading printed on the page — never invented.
 */

// ------------------------------------------------------------------------
// g1-ch1 — introComputersLessons
// ------------------------------------------------------------------------

export const introComputersChapterSummary: string =
  "Chapter 1 is a six-year-old's first eight sittings at a computer, printed pages 4 to 18. It names only three components — the screen, the keyboard and the mouse — then spends the rest of the chapter on where computers are found (home, school, restaurant, factory, airport, pharmacy) and who uses them (students, architects, teachers, restaurant owners). Every lesson pairs its picture page with a GCompris drill: Move the mouse, Click or Tap, Click on Me, Click and draw, Numbers With Dice, Photo hunter, Maze, Draw numbers, Count the items, Number sequence, Enumeration memory game and Addition of numbers — so the child practises moving, clicking, drawing with the mouse, driving with the arrow keys, and counting.";

export const introComputersLessons: Lesson[] = [
  {
    id: "g1-in-01",
    slug: "introduce-the-computer-and-its-components",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 1,
    title: "Introduce the Computer and Its Components",
    description: "Tick who has a computer at home and what it is used for, learn that a computer is made of a screen, a keyboard and a mouse, then copy a screen and a mouse into empty boxes and meet the GCompris welcome screen.",
    objectives: [
      "Objective of lesson 1: Introduce the computer and its components",
      "Computers are everywhere: \"In this first lesson, we will learn about the functions of a computer as well as its most important components.\"",
      "Definition of a computer: \"A computer is designed by humans to accomplish a specific task.\" \"The computer is used everywhere: at home, at school, in the restaurant, in the factory, etc...\"",
      "How is a computer used? It is used to: Calculate / Draw / Watch Cartoons / Listen to music",
      "The computer's components: \"A computer is made of several parts; the most important ones are the screen, the keyboard and the mouse.\"",
      "GCOMPRIS: \"The GCOMPRIS program contains activities that help you use your computer better. One of the most important activities is how to use the mouse and the keyboard.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-02",
    slug: "know-where-computers-are-used",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 2,
    title: "Know Where Computers Are Used",
    description: "Say who invented the computer and where computers are found, then open GCompris and use \"Move the mouse\" and \"Click or Tap\" to rub the cubes off a hidden photo.",
    objectives: [
      "Objectives of lesson 2: Know where computers are used - Master the use of the computer mouse",
      "Warm up practice: Who invented the computer? The doctor / The teacher / The engineer — Mention some places where the computer is used",
      "Where is the computer used? \"Computers are used in most places and professions.\" School / Restaurant / Home / Factory",
      "GCOMPRIS: \"It's time to use the GCOMPRIS program to master the use of the computer mouse.\" Click on Move the mouse to start the activity where you practise moving the mouse — Move the mouse in all directions to erase the cubes covering the image — When you clear all the cubes, you move to a new level of the game",
      "GCOMPRIS: \"It's time to open GCOMPRIS to master the use of the computer mouse.\" Click on Click or Tap to open the activity — Click on the cubes to be erased — At the end of the activity, the entire background image appears",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-03",
    slug: "a-click-or-two",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 3,
    title: "A Click or Two?",
    description: "Learn what the mouse is for, that most jobs need one left-click and that a Desktop icon needs a double-click, then click the fish swimming past in GCompris \"Click on Me\".",
    objectives: [
      "Objective of lesson 3: Master the use of the computer mouse",
      "Definition: \"The computer mouse is one of the basic components used to:\" Run a program / Draw an illustration / Turn off the computer / Write a document",
      "A click or two?: \"To use a computer mouse correctly, learn how to click once or twice.\" \"Most of the time, you need a single left-click of the mouse in order to:\" Draw / Select a word",
      "Running a program: \"To run a program where the icon is on the Desktop of the computer, double-click on the program icon.\"",
      "Click on me!: Click on \"Click on Me\" to launch the activity that teaches you how to click on a computer mouse — Click on the fish that passes in front of you on the screen",
      "Tablet or phone!: \"Are tablets and mobile phones used for the same purpose as computers? Justify your answer.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-04",
    slug: "who-uses-a-computer",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 4,
    title: "Who Uses a Computer?",
    description: "Match jobs to the computers they use — pharmacy, school, airport, restaurant — then complete drawings in GCompris \"Click and draw\" by clicking the green circles.",
    objectives: [
      "Objective of lesson 4: Master the use of the computer mouse",
      "Who uses a computer?: \"The computer has several uses.\" Students use a computer to study, draw, write a text or listen to music / Architects use a computer to draw geometric shapes for houses / Owners of a restaurant use a computer to issue invoices to customers / Teachers use a computer to give online lessons and to prepare exercises",
      "Practice: \"Join the two halves of the sentences.\"",
      "Mastering computer mouse: Click on \"Click and draw\" to launch the activity that helps you master the click of the mouse — Click on the green circle to complete the drawing",
      "Practice: \"Summarize in a short sentence what you have learned so far: The components of a computer are… A computer is used to… A computer is found in…\"",
      "Join the dots: \"It's time to use GCOMPRIS to be able to master the click of the mouse.\"",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-05",
    slug: "counting-numbers-and-spotting-the-differences",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 5,
    title: "Counting Numbers and Spotting the Differences",
    description: "Type the number shown on falling dice in GCompris \"Numbers With Dice\", write six sums on the page, then find the differences between two pictures with \"Photo hunter\".",
    objectives: [
      "Objectives of lesson 5: Count numbers - Compare two pictures to spot the differences",
      "Counting numbers: \"Gcompris allows you to develop skills in math.\" Launch Gcompris — Click on Numbers With Dice — Type the numbers shown on the screen",
      "\"Complete the following exercise by adding the numbers and writing their sum.\"",
      "Spotting the differences: \"Gcompris allows you to use the 'photo hunter' exercise to spot the differences between two images.\" Launch Gcompris — Click on \"photo hunter\" — Mark the differences between the two images shown in front of you",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-06",
    slug: "arrow-keys-exercise",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 6,
    title: "Arrow Keys Exercise",
    description: "Drive a penguin through a maze to the exit door with the keyboard arrow keys, write the path as arrows in an empty grid, then trace numbers by clicking blue circles in \"Draw numbers\".",
    objectives: [
      "Objective of lesson 6: Control the movement of the penguin using the keyboard arrow keys",
      "Arrow keys exercise: \"Gcompris allows you to use various activities to acquire the ability to use the arrow keys of the keyboard.\" Launch Gcompris — From the home screen, click on [the maze activity] — Use the arrow keys to guide the penguin to the exit door",
      "Connect the dots: \"The Gcompris program allows you to use the 'Draw Numbers' exercise to acquire skills in drawing numbers.\" Launch Gcompris — From the welcome screen, click on \"Draw numbers\" — Click on the blue circle to draw the number",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-07",
    slug: "fruit-count-and-sequence-of-numbers",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 7,
    title: "Fruit Count and Sequence of Numbers",
    description: "Count apples and lemons on the GCompris turtle and type the totals, then click and link the numbers 13 to 25 in the correct order.",
    objectives: [
      "Objective of lesson 7: Enumerate numbers",
      "Fruit count practice: \"The Gcompris program allows you to use various activities to be able to count objects.\" Launch Gcompris — From the welcome screen, click on Count the items — Type the number of fruits shown on the screen — Type the number of apples and lemons and apples shown on the screen",
      "Sequence of numbers: \"The Gcompis program allows you to use the 'Number Sequence' exercise to acquire the skill of enumerating the numbers correctly.\" Launch Gcompris — From the home screen, click on \"Number sequence\" activity — Click on the numbers in the correct sequence — Link the circles in the correct sequence order",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-in-08",
    slug: "focus-activities-and-adding-numbers",
    gradeId: "g1",
    unitId: "g1-intro-computers",
    order: 8,
    title: "Focus Activities and Adding Numbers",
    description: "Play the GCompris memory game by turning two cards at a time to find matching pairs, then add the numbers shown in the balloon activity and type the result.",
    objectives: [
      "Objective of lesson 8: Practice memory and math activities with Gcompris",
      "Focus activities: \"Gcompris allows you to use various activities to be able to refresh the memory.\" Launch Gcompris — From the welcome screen, click on Enumeration memory game — Click on two cards to open them. You win if the cards match — If the two cards do not match, they will be closed to try again",
      "Adding numbers: \"Gcompris allows you to use various activities to be able to practise adding numbers.\" From the welcome screen, click on [Addition of numbers] — Add the numbers displayed on the screen then type the result",
    ],
    skillIds: ["sys-hardware", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Monitor",
    status: "coming-soon",
    stages: [],
  },
];

// ------------------------------------------------------------------------
// g1-ch2 — paintLessons
// ------------------------------------------------------------------------

export const paintChapterSummary: string =
  "Chapter 2 is six lessons in Microsoft Paint, printed pages 20 to 30, and it introduces the tools in a fixed order: Shapes and the rectangle, Color 1 for the outline, Color 2 with Fill > Solid color for the inside, then Brushes (Crayon, Natural pencil, Calligraphy brush 1), Size, File > Save, Select with Copy and Paste, the Pen with Fill Color, and finally Resize and skew. The shapes it names are the rectangle, triangle, oval shape, line, star and arrow. Each lesson ends with a plate to reproduce — a robot face of rectangles, a coloured shape sheet, a house and an apple tree, a duplicated house scene, a car, and closing step-by-step plates for a fish and a robot.";

export const paintLessons: Lesson[] = [
  {
    id: "g1-pa-01",
    slug: "launch-paint-and-draw-squares",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 1,
    title: "Launch Paint and Draw Squares",
    description: "Find Paint from the Start menu, look over its menu and drawing tools, then use Shapes and the rectangle in red and black to build a robot's face.",
    objectives: [
      "Objectives of lesson 1: Introduce the program Paint - Draw squares",
      "Paint to draw: \"The Paint program allows you to draw on the computer.\" Have you ever used the Paint program? Yes / No — Which icon is for the Paint program?",
      "Launch Paint: \"In order to start drawing using Paint, follow these steps:\" Click on \"Start\" — In the search field, type the word \"paint\" — Click on Paint to launch it — The welcome screen of the \"Paint\" program appears in front of you — Examine the main menu — Examine the drawing tools",
      "Practice: \"Try to launch the Paint program then close it.\"",
      "Drawing squares: \"Drawing shapes is an easy process:\" Click on \"Shapes\" — Choose the \"rectangle\" — Use your mouse to draw a rectangle — Draw a rectangle — Choose the red colour — Draw a red rectangle",
      "Practice: \"Use the rectangle to draw the robot face.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-02",
    slug: "draw-shapes-and-change-the-border-colour",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 2,
    title: "Draw Shapes and Change the Border Colour",
    description: "Name six Paint shapes, draw an arrow and a star, use Color 1 to change the outline colour and Color 2 with Fill > Solid color to change the inside colour.",
    objectives: [
      "Objectives of lesson 2: Draw shapes - Change the shape and the border colour",
      "Changing shapes: \"In this exercise, we will learn about some of the shapes that can be drawn using the 'Paint' program.\" \"Match each term with the corresponding shape.\" Triangle / Oval shape / Rectangle / Line / Star / Arrow",
      "Drawing shapes: \"To draw shapes with different colours, follow these steps:\" Click on Shapes — Choose the shape you want to draw — Check the available shapes — Draw an arrow then a star",
      "Color the shape's contour: \"If you want to draw shapes with different contour colours, follow these steps:\" Click on \"Color 1\" — Choose the color you want to use — Draw the shape you want — Notice how the contour of the arrow is green",
      "Changing the inside colour of a shape: \"It's time to learn how to change the inside colour of a shape.\" Click on \"Color 2\" — Choose the color you want — Click on Fill, then choose Solid Color — Draw the star — Look how the star is painted in yellow",
      "Practice: \"Draw the following shapes using the same colours.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-03",
    slug: "draw-with-a-brush-and-save-the-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 3,
    title: "Draw with a Brush and Save the Drawing",
    description: "Pick a brush head — Crayon, Natural pencil or Calligraphy brush 1 — change its Size, draw a house and an apple tree, then save the picture with File > Save.",
    objectives: [
      "Objectives of lesson 3: Draw shapes using a brush - Change the brush size - Save a drawing",
      "Using the brush for beautiful drawings: \"It's time to use the brush to draw new shapes.\" Select the Brush button — Choose the shape of the brush you want to use — The Crayon brush — A brush that paints in the form of a \"Natural pencil\" — Calligraphy brush 1",
      "Practice: \"Use the geometric shapes and the brush to reproduce the following drawing.\"",
      "Changing the brush size: \"To use the brush in different sizes, click on 'Size'.\" Choose the size you want then start drawing",
      "Saving the drawing: \"When you finish drawing, and before closing the 'Paint' program, you must save the drawing on your computer.\" Click on \"File\" — Click on \"Save\" — Type the file name — Click on \"Save\" — You can now exit the Paint program — \"The drawing is on your computer. You can open it again whenever you want.\"",
      "Practice: \"Use the Paint program to draw a sun and a moon, then save the drawing on your computer.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-04",
    slug: "select-and-copy-paste-a-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 4,
    title: "Select and Copy/Paste a Drawing",
    description: "Reproduce a house-and-sun picture, then use Select, Copy and Paste to duplicate the whole drawing and slide the copy to the right.",
    objectives: [
      "Objectives of lesson 4: Select a drawing - Copy/Paste a drawing",
      "Copying and Pasting: \"In this lesson, we will learn how to select a graphic in order to copy it and duplicate it.\"",
      "\"Reproduce the drawing below in the same colour.\"",
      "Click on Select — Select the drawing you want to copy — Click on Copy — Click on \"paste\" — Move the copied shape to the right",
      "Note: \"To master the use of the selection skills, watch the tutorial on the book's digital platform www.zero1.education.\"",
      "Practice: \"Redraw the fish then reproduce it on the Paint program. Save it on the computer.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-05",
    slug: "copy-paste-and-resize-a-drawing",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 5,
    title: "Copy, Paste and Resize a Drawing",
    description: "Draw a car with the Pen, colour it with Fill Color and add the wheels, then shrink it with Select and Resize and skew by percentage.",
    objectives: [
      "Objectives of lesson 5: Copy and Paste a drawing - Change the size of a drawing",
      "An image to draw: \"In this lesson, we will learn the steps to draw a car.\" Look at the shape of the car — Choose the Pen then select the size — Draw the car Skeleton — Click on \"Fill Color\" to change the colour of the car — Draw the wheels",
      "Changing the image size: \"It is time to learn how to change the size of the car by following simple steps.\" Select the graphic you want to resize — Click on \"Resize and skew\" — Select the reduction or enlargement percentage, then click on OK — Examine the result",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
  {
    id: "g1-pa-06",
    slug: "drawing-a-fish-and-a-robot-with-paint",
    gradeId: "g1",
    unitId: "g1-paint",
    order: 6,
    title: "Drawing a Fish and a Robot with Paint",
    description: "Two closing plates: build a fish in six drawing stages and a robot in three, then colour them in.",
    objectives: [
      "Objective of lesson 6: Drawing a fish and a robot with Paint",
      "An image to draw: \"Use your drawing skills to draw a fish.\"",
      "A robot to draw: \"Use your drawing skills to draw a robot.\"",
    ],
    skillIds: ["cr-projects", "dl-files"],
    estimatedMinutes: 30,
    difficulty: "intro",
    icon: "Brush",
    status: "coming-soon",
    stages: [],
  },
];
